# Generated by Django 5.2 on 2025-09-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachercert', '0132_alter_ceuinstance_file_and_more'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, help_text='Scheduled date of the visit.', null=True)),
                ('representative', models.CharField(blank=True, help_text='Name of the ISEI representative who led the visit.', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_visits', to='users.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_visits', to='teachercert.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text='Google Drive folder link', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_documents', to='users.school')),
            ],
        ),
    ]
