# Generated by Django 5.2 on 2025-09-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annualvisit', '0001_initial'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolDocuments',
            new_name='SchoolDocument',
        ),
    ]
