# Generated by Django 5.2 on 2025-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annualvisit', '0002_rename_schooldocuments_schooldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldocument',
            name='first_accreditation_link',
            field=models.URLField(blank=True, help_text='Google Drive folder link - Accreditation Docs', null=True),
        ),
    ]
