# Generated by Django 5.2 on 2026-05-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annualvisit', '0003_schooldocument_first_accreditation_link'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolDocument',
            new_name='SchoolDocumentLink',
        ),
    ]
