# Generated by Django 3.2 on 2021-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the school', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, help_text='Enter the name of the school', max_length=50, null=True)),
                ('abbreviation', models.CharField(default=' ', help_text=' Enter the abbreviation for this school', max_length=4)),
            ],
        ),
    ]
