# Generated by Django 3.2 on 2021-04-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_certification', models.CharField(blank=True, choices=[('b', 'Basic'), ('c', 'Conditional'), ('d', 'Designated'), ('e', 'Semi Professional'), ('n', 'None'), ('p', 'Professional'), ('s', 'Standard'), ('v', 'Vocational')], max_length=1, null=True)),
                ('school', models.ForeignKey(help_text='*Required', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
