# Generated by Django 3.2 on 2021-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='ProfilePictures/blank-profile.jpg', null=True, upload_to='ProfilePictures/'),
        ),
    ]
