# Generated by Django 3.2 on 2021-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(choices=[('a', 'Asia'), ('e', 'Europe'), ('n', 'North America')], max_length=1)),
            ],
        ),
    ]
