# Generated by Django 3.2 on 2021-08-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='users.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, help_text='Enter the address of the school', max_length=50, null=True),
        ),
    ]
