# Generated by Django 3.2 on 2021-08-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210813_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='current_certification',
        ),
    ]
