# Generated by Django 3.2 on 2021-08-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210817_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='initial',
            field=models.BooleanField(default=True),
        ),
    ]
