# Generated by Django 3.2 on 2021-08-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_application_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeattended',
            name='transcript_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegeattended',
            name='transcript_requested',
            field=models.BooleanField(default=False),
        ),
    ]
