# Generated by Django 3.2 on 2021-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210818_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='transcripts_requested',
        ),
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_requested',
            field=models.BooleanField(default=False, verbose_name='Official college transcripts have been requested'),
        ),
    ]
