# Generated by Django 3.2 on 2021-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210818_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='TeacherCertificationApplication',
        ),
    ]
