# Generated by Django 3.2 on 2021-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_application_teachercertificationapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
