# Generated by Django 3.2 on 2021-08-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_teacher_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.school'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='principal_letter',
            field=models.BooleanField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='N/A', max_length=1, verbose_name='Letter of Recommendation from Principal has been sent (for Designated and Vocational)'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='resume',
            field=models.BooleanField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='N/A', max_length=1, verbose_name='Resume of work/teaching experience is included (for Designated and Vocational)'),
        ),
    ]
