# Generated by Django 3.2 on 2021-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210818_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='principal_letter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='N/A', max_length=1, verbose_name='Letter of Recommendation from Principal has been sent (for Designated and Vocational)'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='resume',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='N/A', max_length=1, verbose_name='Resume of work/teaching experience is included (for Designated and Vocational)'),
        ),
    ]
