# Generated by Django 3.2 on 2021-08-18 21:32

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210818_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='ssn',
            field=localflavor.us.models.USSocialSecurityNumberField(blank=True, max_length=11, null=True),
        ),
    ]
