# Generated by Django 3.2 on 2021-08-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210819_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='name',
            field=models.CharField(max_length=30, verbose_name='College Name'),
        ),
    ]
