# Generated by Django 3.2 on 2021-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_collegeattended_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_received',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
