# Generated by Django 3.2 on 2021-08-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_collegeattended_transcript_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_received',
            field=models.BooleanField(default=False),
        ),
    ]
