# Generated by Django 3.2 on 2021-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20210820_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='principal_letter',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='a', max_length=1, verbose_name='Letter of Recommendation from Principal has been sent (for Designated and Vocational)'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='resume',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='a', max_length=1, verbose_name='Resume of work/teaching experience is included (for Designated and Vocational)'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='subject_areas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Subject Areas'),
        ),
    ]
