# Generated by Django 3.2 on 2021-08-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_teachercertificationapplication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='cert_level',
            field=models.CharField(blank=True, choices=[('v', 'Vocational'), ('s', 'Secondary'), ('e', 'Elementary'), ('d', 'Designated')], max_length=1, null=True, verbose_name='Certification Level Requested'),
        ),
    ]
