# Generated by Django 3.2 on 2021-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_teachercertificationapplication_cert_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='isei_processed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
