# Generated by Django 3.2 on 2021-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_teachercertificationapplication_isei_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercertificationapplication',
            name='isei_processed',
        ),
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='isei_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
