# Generated by Django 3.2 on 2021-08-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20210822_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCertificationApplication',
        ),
    ]
