# Generated by Django 3.2 on 2021-08-24 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_teacher_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='ssn',
        ),
        migrations.AddField(
            model_name='teacher',
            name='joined_at',
            field=models.DateField(default=datetime.date(2021, 8, 24)),
        ),
    ]
