# Generated by Django 3.2.6 on 2021-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210824_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeattended',
            name='transcript_processed',
            field=models.BooleanField(default=False),
        ),
    ]
