# Generated by Django 3.2.6 on 2021-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_collegeattended_transcript_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joined_at',
            field=models.DateField(),
        ),
    ]
