# Generated by Django 3.2.6 on 2021-08-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_teacher_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('school', 'last_name')},
        ),
    ]
