# Generated by Django 3.2.6 on 2021-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_teacher_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='end_date',
            field=models.CharField(help_text='mm/dd/yyyy or yyyy', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeattended',
            name='start_date',
            field=models.CharField(help_text='mm/dd/yyyy or yyyy', max_length=10),
        ),
    ]
