# Generated by Django 3.2.6 on 2021-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20210901_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='name',
            field=models.CharField(max_length=35, verbose_name='College Name'),
        ),
    ]
