# Generated by Django 3.2.6 on 2021-09-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_collegeattended_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='degree',
            field=models.CharField(blank=True, help_text='BSc, Marketing & Psychology', max_length=40, null=True, verbose_name='Type, Degree Earned'),
        ),
        migrations.AlterField(
            model_name='collegeattended',
            name='level',
            field=models.CharField(choices=[('a', 'Associate degree'), ('b', "Bachelor's degree"), ('m', "Master's degree"), ('d', 'Doctoral degree'), ('n', 'None')], help_text='Degree Level', max_length=1),
        ),
    ]
