# Generated by Django 3.2.6 on 2021-09-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20210901_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofemployment',
            name='end_date',
            field=models.CharField(help_text='mm/dd/yyyy or to date', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolofemployment',
            name='start_date',
            field=models.CharField(help_text='mm/dd/yyyy', max_length=10),
        ),
    ]
