# Generated by Django 3.2.6 on 2021-09-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20210901_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofemployment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
