# Generated by Django 3.2.6 on 2021-09-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_schoolofemployment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeattended',
            options={'ordering': ('-end_date',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='schoolofemployment',
            options={'ordering': ('-end_date',)},
        ),
    ]
