# Generated by Django 3.2.6 on 2021-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20210906_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='name',
            field=models.CharField(max_length=60, verbose_name='College Name'),
        ),
    ]
