# Generated by Django 3.2.6 on 2021-09-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_collegeattended_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeattended',
            options={'ordering': ('teacher', '-end_date')},
        ),
    ]
