# Generated by Django 3.2.6 on 2021-09-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_alter_collegeattended_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegeattended',
            options={'ordering': ('transcript_processed', 'transcript_received', 'transcript_requested', 'teacher', '-end_date')},
        ),
    ]
