# Generated by Django 3.2.6 on 2021-09-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20210915_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_received',
            field=models.BooleanField(default=False, verbose_name='Received'),
        ),
        migrations.AlterField(
            model_name='collegeattended',
            name='transcript_requested',
            field=models.BooleanField(default=False, verbose_name='Transcripts requested'),
        ),
    ]
