# Generated by Django 3.2.6 on 2021-09-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20210915_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeattended',
            name='level',
            field=models.CharField(choices=[('a', 'Associate degree'), ('b', "Bachelor's degree"), ('m', "Master's degree"), ('d', 'Doctoral degree'), ('c', 'Certificate'), ('n', 'None')], help_text='Degree Level', max_length=1),
        ),
    ]
