# Generated by Django 3.2.6 on 2021-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_alter_collegeattended_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofemployment',
            name='end_date',
            field=models.CharField(help_text="mm/yyyy or yyyy or 'to date'", max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolofemployment',
            name='start_date',
            field=models.CharField(help_text='mm/yyyy or yyyy', max_length=10),
        ),
    ]
