# Generated by Django 3.2.6 on 2021-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20211118_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='foundation',
            field=models.BooleanField(default=False),
        ),
    ]
