# Generated by Django 3.2.6 on 2021-11-22 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_school_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joined_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
