# Generated by Django 3.2.6 on 2022-03-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20220207_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academic',
            field=models.BooleanField(default=True),
        ),
    ]
