# Generated by Django 3.2.6 on 2022-03-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_teacher_academic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academic',
        ),
    ]
