# Generated by Django 3.2.6 on 2022-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_remove_teacher_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
    ]
