# Generated by Django 3.2.6 on 2023-11-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_teacher_background_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='state_old',
        ),
    ]
