# Generated by Django 3.2.6 on 2024-05-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20240503_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.region'),
        ),
    ]
