# Generated by Django 3.2.6 on 2024-05-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region2',
        ),
    ]
