# Generated by Django 3.2.6 on 2024-05-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state_old',
        ),
    ]
