# Generated by Django 3.2.6 on 2024-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_remove_address_state_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='TN_County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
