# Generated by Django 3.2.6 on 2024-05-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_tn_county'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TN_County',
            new_name='TNCounty',
        ),
    ]
