# Generated by Django 3.2.6 on 2024-05-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_rename_tn_county_tncounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tn_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tncounty'),
        ),
    ]
