# Generated by Django 3.2.6 on 2024-05-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20240516_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_accreditation', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'unique_together': {('school', 'agency_name', 'current_accreditation')},
            },
        ),
    ]
