# Generated by Django 3.2.6 on 2024-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_accreditationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
