# Generated by Django 3.2.6 on 2024-05-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_accreditationagency_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationinfo',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.accreditationagency'),
        ),
        migrations.AlterUniqueTogether(
            name='accreditationinfo',
            unique_together={('school', 'agency', 'current_accreditation')},
        ),
        migrations.RemoveField(
            model_name='accreditationinfo',
            name='agency_name',
        ),
    ]
