# Generated by Django 3.2.6 on 2024-05-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20240517_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationinfo',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accreditationagency'),
        ),
    ]
