# Generated by Django 3.2.6 on 2024-05-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_alter_accreditationinfo_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tncounty',
            options={'ordering': ['name']},
        ),
    ]
