# Generated by Django 3.2.6 on 2024-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_school_textapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='student_occurrence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
