# Generated by Django 3.2.6 on 2024-06-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_country_student_occurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['student_occurrence', 'name']},
        ),
    ]
