# Generated by Django 3.2.6 on 2024-06-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-student_occurrence', 'name']},
        ),
    ]
