# Generated by Django 3.2.6 on 2024-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='student_occurrence_log',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
