# Generated by Django 3.2.6 on 2024-06-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_country_student_occurrence_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-student_occurrence_log', 'name']},
        ),
    ]
