# Generated by Django 3.2.6 on 2024-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('K-8', 'K-8'), ('K-12', 'K-12'), ('9-12', '9-12')], default='9-12', max_length=5, verbose_name='Type of School'),
        ),
    ]
