# Generated by Django 3.2.6 on 2024-07-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0126_alter_ceuinstance_options'),
        ('users', '0103_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear'),
        ),
    ]
