# Generated by Django 3.2 on 2024-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_school_fire_marshal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fire_marshal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Last Fire Marshal Inspection'),
        ),
    ]
