# Generated by Django 3.2 on 2024-09-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_alter_school_fire_marshal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
