# Generated by Django 3.2 on 2024-11-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_school_worthy_student_report_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default=' ', help_text=' Enter the abbreviation for this school', max_length=6),
        ),
    ]
