# Generated by Django 3.2 on 2025-01-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_alter_school_abbreviation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccreditationInfo',
            new_name='OtherAgencyAccreditationInfo',
        ),
    ]
