# Generated by Django 3.2 on 2025-02-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_schooltype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schooltype',
            table='users_schooltype',
        ),
    ]
