# Generated by Django 3.2 on 2025-02-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_auto_20250202_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grade_levels',
            field=models.CharField(choices=[('K-8', 'K-8'), ('K-12', 'K-12'), ('9-12', '9-12')], default='9-12', max_length=5, verbose_name='Grade Levels'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schooltype', verbose_name='School Type'),
        ),
    ]
