# Generated by Django 3.2 on 2025-02-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_auto_20250202_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='board_chair',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
