# Generated by Django 5.2 on 2025-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_school_board_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='schooltype',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type_choice',
            field=models.ManyToManyField(blank=True, to='users.schooltypechoice', verbose_name='School Type (Selected by School)'),
        ),
    ]
