# Generated by Django 5.2 on 2025-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_schooltypechoice_schooltype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default=' ', max_length=6),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
