# Generated by Django 5.2 on 2025-04-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_alter_school_abbreviation_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='board_chair_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='board_chair_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='year_school_started',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
