# Generated by Django 5.2 on 2025-04-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_school_board_chair_email_school_board_chair_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='date_hired',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
