# Generated by Django 5.2 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_school_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
