# Generated by Django 5.2 on 2025-04-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_alter_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='postal_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_postal', to='users.address'),
        ),
        migrations.AddField(
            model_name='school',
            name='street_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_street', to='users.address'),
        ),
    ]
