# Generated by Django 5.2 on 2025-04-22 14:30

from django.db import migrations

def forwards(apps, schema_editor):
    School = apps.get_model('users', 'School')
    Address = apps.get_model('users', 'Address')

    for address in Address.objects.exclude(school=None):
        school = address.school
        if school and not school.street_address:
            school.street_address = address
            school.save()

def backwards(apps, schema_editor):
    School = apps.get_model('users', 'School')
    for school in School.objects.exclude(street_address=None):
        school.street_address = None
        school.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_school_postal_address_school_street_address'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
