# Generated by Django 5.2 on 2025-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_migrate_address_to_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grade_levels',
            field=models.CharField(choices=[('K-8', 'K-8'), ('K-12', 'K-12'), ('9-12', '9-12'), ('GAI-III', 'GAI-III')], default='9-12', max_length=10, verbose_name='Grade Levels'),
        ),
    ]
