# Generated by Django 5.2 on 2025-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_alter_school_grade_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='school',
        ),
    ]
