# Generated by Django 5.2 on 2025-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_remove_address_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='board_chair_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
