# Generated by Django 5.2 on 2025-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_alter_school_board_chair_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grade_levels',
            field=models.CharField(choices=[('K-8', 'K-8'), ('K-12', 'K-12'), ('9-12', '9-12'), ('5-12', '5-12'), ('GAI-III', 'GAI-III')], default='9-12', max_length=10, verbose_name='Grade Levels'),
        ),
    ]
