# Generated by Django 5.2 on 2026-05-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_users', to='users.school'),
        ),
        migrations.CreateModel(
            name='UserSchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='users.school')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_schools',
            field=models.ManyToManyField(blank=True, related_name='members', through='users.UserSchoolMembership', to='users.school'),
        ),
        migrations.AddConstraint(
            model_name='userschoolmembership',
            constraint=models.UniqueConstraint(fields=('user_profile', 'school'), name='unique_user_school_membership'),
        ),
    ]
