# Generated by Django 5.2 on 2026-05-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_alter_userprofile_school_userschoolmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userschoolmembership',
            name='unique_user_school_membership',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='available_schools',
        ),
        migrations.RemoveField(
            model_name='userschoolmembership',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userschoolmembership',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.school'),
        ),
        migrations.AddConstraint(
            model_name='userschoolmembership',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='unique_user_school_membership'),
        ),
    ]
