# Generated by Django 5.2 on 2026-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_remove_userschoolmembership_unique_user_school_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
