# Generated by Django 3.2.6 on 2024-07-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0104_school_current_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Reusable Test Booklets'), (2, 'Answer Sheets'), (3, 'Admin Directions Booklet'), (4, 'Test Scoring')])),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_dates', models.CharField(blank=True, max_length=255, null=True, verbose_name='Testing dates')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order date')),
                ('sub_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sub total')),
                ('shipping', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Shipping')),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.school')),
            ],
        ),
        migrations.CreateModel(
            name='TestMaterialOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(9, 'Grade 3, Level 9'), (10, 'Grade 4, Level 10'), (11, 'Grade 5, Level 11'), (12, 'Grade 6, Level 12'), (13, 'Grade 7, Level 13'), (14, 'Grade 8, Level 14'), (15, 'Grade 9, Level 15'), (16, 'Grade 10, Level 16'), (17, 'Grade 11-12, Level 17/18')])),
                ('direction_choice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direction')),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.testmaterialtype')),
            ],
        ),
    ]
