# Generated by Django 3.2.6 on 2024-07-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240714_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterialtype',
            name='name',
            field=models.IntegerField(choices=[(1, 'Reusable Test Booklet'), (2, 'Answer Sheet'), (3, 'Admin Directions Booklet'), (4, 'Test Scoring')], unique=True),
        ),
    ]
