# Generated by Django 3.2.6 on 2024-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_testmaterialtype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterialtype',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Updated'),
        ),
    ]
