# Generated by Django 3.2.6 on 2024-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_testmaterialtype_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterialtype',
            name='name',
            field=models.IntegerField(choices=[(1, 'Reusable Test Booklet'), (2, 'Answer Sheet'), (3, 'Admin Directions Booklet'), (4, 'Test Scoring'), (5, 'Shipping')], unique=True),
        ),
    ]
