# Generated by Django 3.2.6 on 2024-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_testmaterialtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaterialtype',
            name='name',
            field=models.IntegerField(choices=[(1, 'Reusable Test Booklet'), (2, 'Answer Sheet'), (3, 'Admin Directions Booklet'), (4, 'Test Scoring')], unique=True),
        ),
    ]
