# Generated by Django 3.2.6 on 2024-07-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_testorder_student_testing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='student_testing',
            new_name='no_students_testing',
        ),
    ]
