# Generated by Django 3.2.6 on 2024-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_student_testing_testorder_no_students_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetordered',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='answersheetordered',
            name='level',
            field=models.IntegerField(choices=[(9, 'Grade 3, Level 9'), (10, 'Grade 4, Level 10'), (11, 'Grade 5, Level 11'), (12, 'Grade 6, Level 12'), (13, 'Grade 7, Level 13'), (14, 'Grade 8, Level 14'), (15, 'Grade 9, Level 15'), (16, 'Grade 10, Level 16'), (17, 'Grade 11-12, Level 17/18')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='directionbookletordered',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='directionbookletordered',
            name='level',
            field=models.IntegerField(choices=[(1, 'Grades 3-8, Level 9-14'), (2, 'Grades 9-12 , Level 15-17/18')], verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='reusabletestbookletordered',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='reusabletestbookletordered',
            name='level',
            field=models.IntegerField(choices=[(9, 'Grade 3, Level 9'), (10, 'Grade 4, Level 10'), (11, 'Grade 5, Level 11'), (12, 'Grade 6, Level 12'), (13, 'Grade 7, Level 13'), (14, 'Grade 8, Level 14'), (15, 'Grade 9, Level 15'), (16, 'Grade 10, Level 16'), (17, 'Grade 11-12, Level 17/18')], verbose_name='Level'),
        ),
    ]
