# Generated by Django 3.2.6 on 2024-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20240715_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Shipping'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sub total'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total'),
        ),
    ]
