# Generated by Django 3.2.6 on 2024-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20240715_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='finalized',
            field=models.BooleanField(default=False, verbose_name='Finalized'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name='Submitted'),
        ),
    ]
