# Generated by Django 3.2 on 2024-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20240716_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetordered',
            name='level',
            field=models.IntegerField(choices=[(8, 'Grade 3 without listening, Level 9'), (9, 'Grade 3 with listening, Level 9'), (10, 'Grade 4, Level 10'), (11, 'Grade 5, Level 11'), (12, 'Grade 6, Level 12'), (13, 'Grade 7, Level 13'), (14, 'Grade 8, Level 14'), (15, 'Grade 9, Level 15'), (16, 'Grade 10, Level 16'), (17, 'Grade 11-12, Level 17/18')], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='reusabletestbookletordered',
            name='level',
            field=models.IntegerField(choices=[(8, 'Grade 3 without listening, Level 9'), (9, 'Grade 3 with listening, Level 9'), (10, 'Grade 4, Level 10'), (11, 'Grade 5, Level 11'), (12, 'Grade 6, Level 12'), (13, 'Grade 7, Level 13'), (14, 'Grade 8, Level 14'), (15, 'Grade 9, Level 15'), (16, 'Grade 10, Level 16'), (17, 'Grade 11-12, Level 17/18')], verbose_name='Level'),
        ),
    ]
