# Generated by Django 5.2 on 2025-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_resource_resourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
