# Generated by Django 5.2 on 2026-02-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='no_grades_testing',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of grade levels testing'),
            preserve_default=False,
        ),
    ]
