# Generated by Django 5.2 on 2026-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_testorder_no_grades_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='no_grades_testing',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of grade levels testing'),
        ),
    ]
