# Generated by Django 5.2 on 2026-05-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_testorder_no_grades_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='sublist',
            field=models.BooleanField(default=False),
        ),
    ]
