# Generated by Django 3.2.6 on 2024-05-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0122_auto_20220825_2141'),
        ('users', '0080_auto_20240115_2140'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('withdraw_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(choices=[('on-site', 'On-Site'), ('satelite', 'Satelite'), ('distance-learning', 'Distance-Learning')], default='on-site', max_length=20)),
                ('age_at_registration', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.student')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear')),
                ('student_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporting.studentreport')),
            ],
        ),
    ]
