# Generated by Django 3.2.6 on 2024-05-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_remove_country_region2'),
        ('reporting', '0002_annualreport_studentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDueDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_year_report_due', models.DateField()),
                ('in_service_year_end_report_due', models.DateField()),
                ('annual_progress_report_due', models.DateField()),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.region')),
            ],
            options={
                'verbose_name_plural': 'Report due dates',
            },
        ),
    ]
