# Generated by Django 3.2.6 on 2024-05-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0123_schoolyear_current_school_year'),
        ('users', '0083_remove_country_region2'),
        ('reporting', '0003_reportduedates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreport',
            name='student_report',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='age_at_registration',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentreport',
            name='withdraw_date',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('did_not_return', 'Did Not Return')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='annual_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.annualreport'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('withdraw_date', models.DateField(blank=True, null=True)),
                ('age_at_registration', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('on-site', 'On-Site'), ('satelite', 'Satelite'), ('distance-learning', 'Distance-Learning')], default='on-site', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.student')),
            ],
        ),
        migrations.AddField(
            model_name='studentreport',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.enrollment'),
        ),
    ]
