# Generated by Django 3.2.6 on 2024-05-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0123_schoolyear_current_school_year'),
        ('reporting', '0004_auto_20240505_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreport',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='student',
            name='age_at_registration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('on-site', 'On-Site'), ('satelite', 'Satelite'), ('distance-learning', 'Distance-Learning')], default='on-site', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='withdraw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
