# Generated by Django 3.2.6 on 2024-05-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0123_schoolyear_current_school_year'),
        ('reporting', '0005_auto_20240506_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear'),
        ),
    ]
