# Generated by Django 3.2.6 on 2024-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20240506_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportduedates',
            name='annual_progress_report_due',
        ),
        migrations.RemoveField(
            model_name='reportduedates',
            name='beginning_year_report_due',
        ),
        migrations.RemoveField(
            model_name='reportduedates',
            name='in_service_year_end_report_due',
        ),
        migrations.AddField(
            model_name='reportduedates',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportduedates',
            name='report_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
