# Generated by Django 3.2.6 on 2024-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20240506_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportduedate',
            name='opening_report',
            field=models.BooleanField(default=False),
        ),
    ]
