# Generated by Django 3.2.6 on 2024-05-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_reportduedate_opening_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.AddField(
            model_name='annualreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.report'),
        ),
        migrations.AddField(
            model_name='student',
            name='annual_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reporting.annualreport'),
        ),
        migrations.DeleteModel(
            name='StudentReport',
        ),
    ]
