# Generated by Django 3.2.6 on 2024-05-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20240506_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
    ]
