# Generated by Django 3.2.6 on 2024-05-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_student_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_at_least_one_parent_sda',
            field=models.BooleanField(null=True, verbose_name='Parent SDA?'),
        ),
    ]
