# Generated by Django 3.2.6 on 2024-05-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_at_least_one_parent_sda',
            field=models.BooleanField(null=True, verbose_name='Parent SDA'),
        ),
    ]
