# Generated by Django 3.2.6 on 2024-05-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_alter_student_is_at_least_one_parent_sda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='annual_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reporting.annualreport'),
        ),
    ]
