# Generated by Django 3.2.6 on 2024-05-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_student_tn_county'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
