# Generated by Django 3.2.6 on 2024-05-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportType',
        ),
        migrations.RenameField(
            model_name='annualreport',
            old_name='report',
            new_name='report_type',
        ),
        migrations.RenameField(
            model_name='reportduedate',
            old_name='report',
            new_name='report_type',
        ),
    ]
