# Generated by Django 3.2.6 on 2024-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_auto_20240508_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
