# Generated by Django 3.2.6 on 2024-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_annualreport_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
