# Generated by Django 3.2.6 on 2024-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_alter_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated Last Year'), ('did_not_return', 'Did Not Return')], default=None, max_length=15, null=True),
        ),
    ]
