# Generated by Django 3.2.6 on 2024-05-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0033_auto_20240508_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baptized',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_at_least_one_parent_sda',
            field=models.BooleanField(default=False, null=True, verbose_name='Parent SDA'),
        ),
    ]
