# Generated by Django 3.2.6 on 2024-05-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0034_auto_20240508_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_at_least_one_parent_sda',
            new_name='parent_sda',
        ),
    ]
