# Generated by Django 3.2.6 on 2024-05-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_rename_is_at_least_one_parent_sda_student_parent_sda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baptized',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_sda',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='Parent SDA'),
        ),
    ]
