# Generated by Django 3.2.6 on 2024-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0037_auto_20240512_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age_at_registration',
            field=models.PositiveIntegerField(default=13),
            preserve_default=False,
        ),
    ]
