# Generated by Django 3.2.6 on 2024-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0041_alter_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='oder_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
