# Generated by Django 3.2.6 on 2024-05-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0042_reporttype_oder_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='oder_number',
            new_name='order_number',
        ),
    ]
