# Generated by Django 3.2.6 on 2024-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0043_rename_oder_number_reporttype_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boarding',
            field=models.BooleanField(default=False),
        ),
    ]
