# Generated by Django 3.2.6 on 2024-05-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0045_alter_student_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(choices=[('on-site', 'On-Site'), ('satellite', 'Satellite'), ('distance-learning', 'Distance-Learning')], default='on-site', max_length=20),
        ),
    ]
