# Generated by Django 3.2.6 on 2024-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0123_schoolyear_current_school_year'),
        ('users', '0094_alter_accreditationinfo_agency'),
        ('reporting', '0046_alter_student_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualreport',
            unique_together={('school', 'school_year', 'report_type')},
        ),
    ]
