# Generated by Django 3.2.6 on 2024-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0048_reporttype_for_all_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='isei_created',
            field=models.BooleanField(default=False),
        ),
    ]
