# Generated by Django 3.2.6 on 2024-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_reporttype_isei_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='view_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
