# Generated by Django 3.2.6 on 2024-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0051_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('did_not_return', 'Did Not Return')], default='enrolled', max_length=15),
        ),
    ]
