# Generated by Django 3.2.6 on 2024-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0054_alter_student_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
