# Generated by Django 3.2.6 on 2024-05-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0055_alter_student_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'annual_report')},
        ),
        migrations.CreateModel(
            name='day190_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day190', to='reporting.annualreport')),
            ],
        ),
    ]
