# Generated by Django 3.2.6 on 2024-05-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0056_auto_20240527_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviatedDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Day190',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.PositiveIntegerField()),
                ('number_of_sundays', models.PositiveIntegerField()),
                ('inservice_days', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day190', to='reporting.annualreport')),
            ],
        ),
        migrations.CreateModel(
            name='InserviceDiscretionaryDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CI', 'Curriculum Improvement'), ('II', 'Instructional Improvement'), ('CM', 'Classroom Management'), ('TE', 'Teacher/Administrator Evaluation'), ('TC', 'Teacher Convention'), ('OT', 'Other'), ('DS', 'Discretionary')], default='CI', max_length=2)),
                ('dates', models.CharField(max_length=255)),
                ('hours', models.PositiveIntegerField()),
                ('day190', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inservice_discretionary_days', to='reporting.day190')),
            ],
        ),
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekdays', models.IntegerField()),
                ('day190', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='reporting.day190')),
            ],
        ),
        migrations.DeleteModel(
            name='day190_report',
        ),
        migrations.AddField(
            model_name='abbreviateddays',
            name='day190',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbreviated_days', to='reporting.day190'),
        ),
    ]
