# Generated by Django 3.2.6 on 2024-05-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0057_auto_20240527_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbreviateddays',
            name='dates',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abbreviateddays',
            name='hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
