# Generated by Django 3.2.6 on 2024-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0058_auto_20240528_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='inservice_days',
            field=models.PositiveIntegerField(verbose_name='Inservice and Discretionary Days'),
        ),
    ]
