# Generated by Django 3.2.6 on 2024-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0060_auto_20240528_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='day190',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
