# Generated by Django 3.2.6 on 2024-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0062_rename_dates_abbreviateddays_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='number_of_sundays',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Sunday school days'),
        ),
    ]
