# Generated by Django 3.2.6 on 2024-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0063_alter_day190_number_of_sundays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='School-year end date'),
        ),
        migrations.AlterField(
            model_name='day190',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='School-year start date'),
        ),
    ]
