# Generated by Django 3.2.6 on 2024-05-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0064_auto_20240529_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='number_of_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of School Days'),
        ),
    ]
