# Generated by Django 3.2.6 on 2024-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_alter_day190_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='inservice_days',
            field=models.PositiveIntegerField(default=0, verbose_name='In-service and Discretionary Days'),
        ),
    ]
