# Generated by Django 3.2.6 on 2024-06-04 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0066_alter_day190_inservice_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('presenter', models.CharField(max_length=255)),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.annualreport')),
            ],
        ),
    ]
