# Generated by Django 3.2.6 on 2024-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0068_alter_inservice_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inservice',
            name='hours',
            field=models.PositiveIntegerField(),
        ),
    ]
