# Generated by Django 3.2.6 on 2024-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0069_alter_inservice_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inservicediscretionarydays',
            name='type',
            field=models.CharField(choices=[('CI', 'Curriculum Improvement'), ('II', 'Instructional Improvement'), ('CM', 'Classroom Management'), ('TE', 'Teacher/Administrator Evaluation'), ('TC', 'Teacher Convention'), ('OT', 'Other'), ('DS', 'Discretionary')], max_length=2),
        ),
    ]
