# Generated by Django 3.2.6 on 2024-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0070_alter_inservicediscretionarydays_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='code',
            field=models.CharField(default='ST', max_length=3),
        ),
    ]
