# Generated by Django 3.2.6 on 2024-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0072_educationalenrichmentactivity_sundayschooldays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalenrichmentactivity',
            old_name='dates',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='inservicediscretionarydays',
            name='dates',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sundayschooldays',
            name='date',
            field=models.DateField(),
        ),
    ]
