# Generated by Django 3.2.6 on 2024-06-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0073_auto_20240611_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalenrichmentactivity',
            old_name='date',
            new_name='dates',
        ),
    ]
