# Generated by Django 3.2.6 on 2024-06-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0076_auto_20240611_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sundayschooldays',
            unique_together=set(),
        ),
    ]
