# Generated by Django 3.2.6 on 2024-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0077_alter_sundayschooldays_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day190',
            name='number_of_sundays',
        ),
    ]
