# Generated by Django 3.2.6 on 2024-06-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_alter_country_options'),
        ('reporting', '0080_auto_20240612_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('VO', 'Volunteer'), ('NE', 'No Longer Employed'), ('LO', 'Leave of Absence')], default='FT', max_length=2, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='years_at_this_school',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('B', 'Bible'), ('C', 'Computer/Tech'), ('F', 'Fine Arts'), ('L', 'Language Arts'), ('M', 'Math'), ('ML', 'Modern Language'), ('SC', 'Science'), ('SS', 'Social Studies'), ('V', 'Vocational Arts Courses'), ('W', 'Wellness/Health/PE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PersonnelSubjectAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.personnel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Associate', 'Associate'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Professional', 'Professional')], max_length=30)),
                ('area_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.areaofstudy')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='subjects_taught',
            field=models.ManyToManyField(through='reporting.PersonnelSubjectAll', to='reporting.Subject'),
        ),
    ]
