# Generated by Django 3.2.6 on 2024-06-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0081_auto_20240613_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Position',
            new_name='StaffPosition',
        ),
        migrations.AddField(
            model_name='personnel',
            name='degrees',
            field=models.ManyToManyField(through='reporting.PersonnelDegree', to='reporting.Degree'),
        ),
        migrations.AlterField(
            model_name='personneldegree',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.degree'),
        ),
    ]
