# Generated by Django 3.2.6 on 2024-06-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0082_auto_20240613_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaofstudy',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='degree_name',
            new_name='name',
        ),
    ]
