# Generated by Django 3.2.6 on 2024-06-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0083_auto_20240613_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonnelSubjectAll',
            new_name='PersonnelSubjectTaught',
        ),
        migrations.AlterModelOptions(
            name='staffposition',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['category', 'name']},
        ),
    ]
