# Generated by Django 3.2.6 on 2024-06-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0084_auto_20240613_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('first_name', 'last_name', 'annual_report')},
        ),
    ]
