# Generated by Django 3.2.6 on 2024-06-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0085_alter_personnel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneldegree',
            name='area_of_study',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AreaOfStudy',
        ),
    ]
