# Generated by Django 3.2.6 on 2024-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0086_auto_20240614_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='subjects_taught',
        ),
        migrations.DeleteModel(
            name='PersonnelSubjectTaught',
        ),
    ]
