# Generated by Django 3.2.6 on 2024-06-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0087_auto_20240614_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='subjects_taught',
            field=models.ManyToManyField(to='reporting.Subject'),
        ),
    ]
