# Generated by Django 3.2.6 on 2024-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0090_alter_personnel_subjects_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='positions',
        ),
        migrations.AddField(
            model_name='personnel',
            name='subjects_teaching',
            field=models.ManyToManyField(blank=True, related_name='subjects_teaching', to='reporting.Subject'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='degrees',
            field=models.ManyToManyField(blank=True, through='reporting.PersonnelDegree', to='reporting.Degree'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='subjects_taught', to='reporting.Subject'),
        ),
        migrations.DeleteModel(
            name='PersonnelPosition',
        ),
    ]
