# Generated by Django 3.2.6 on 2024-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0091_auto_20240616_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='positions',
            field=models.ManyToManyField(to='reporting.StaffPosition'),
        ),
    ]
