# Generated by Django 3.2.6 on 2024-06-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0092_personnel_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffposition',
            name='category',
            field=models.CharField(choices=[('A', 'Administrative'), ('T', 'Teaching'), ('G', 'General Staff')], max_length=50),
        ),
    ]
