# Generated by Django 3.2.6 on 2024-06-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0094_alter_staffposition_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='expiration_date',
        ),
    ]
