# Generated by Django 3.2.6 on 2024-06-18 06:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0095_auto_20240616_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
    ]
