# Generated by Django 3.2.6 on 2024-06-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0096_personnel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='phone_number',
        ),
    ]
