# Generated by Django 3.2.6 on 2024-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0098_personnel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='years_at_this_school',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
