# Generated by Django 3.2.6 on 2024-06-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0099_alter_personnel_years_at_this_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayschooldays',
            name='type',
            field=models.CharField(choices=[(None, '--------------'), ('RC', 'Regular Classes'), ('FT', 'Field Trip'), ('OT', 'Other Education Enrichment Activity'), ('ST', 'Standardized Testing'), ('GR', 'Graduation')], max_length=2),
        ),
    ]
