# Generated by Django 3.2.6 on 2024-06-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0100_alter_sundayschooldays_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_k_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('k_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_1_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_2_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_3_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_4_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_5_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_6_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_7_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_8_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_9_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_10_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_11_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_12_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('graduated_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('did_not_return_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('girl_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('boy_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_girl_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_boy_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baptized_parent_sda_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baptized_parent_non_sda_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unbaptized_parent_sda_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unbaptized_parent_non_sda_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teacher_admin_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('general_staff_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('non_sda_teacher_admin_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('less_BA_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BA_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('MA_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('PhD_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('professional_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_k_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('k_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_1_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_2_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_3_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_4_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_5_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_6_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_7_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_8_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_9_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_10_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_11_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade_12_end_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('withdrawn_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='reporting.annualreport')),
            ],
        ),
    ]
