# Generated by Django 3.2.6 on 2024-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0103_alter_personnel_sda'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='grade_0_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='grade_0_end_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='baptized_parent_non_sda_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with non-SDA parents'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='baptized_parent_sda_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with at least one parents SDA'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='unbaptized_parent_non_sda_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with non-SDA parents'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='unbaptized_parent_sda_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with at least one parents SDA'),
        ),
    ]
