# Generated by Django 3.2.6 on 2024-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0104_auto_20240623_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('did_not_return', 'Did Not Return'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=15),
        ),
    ]
