# Generated by Django 3.2.6 on 2024-06-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0106_auto_20240623_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='baptized_parent_non_sda_count',
            new_name='baptized_parent_non_sda_count_E',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='baptized_parent_sda_count',
            new_name='baptized_parent_sda_count_E',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='unbaptized_parent_non_sda_count',
            new_name='unbaptized_parent_non_sda_count_E',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='unbaptized_parent_sda_count',
            new_name='unbaptized_parent_sda_count_E',
        ),
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_non_sda_count_K',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with non-SDA parents K'),
        ),
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_non_sda_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with non-SDA parents S'),
        ),
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_sda_count_K',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with at least one parents SDA K'),
        ),
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_sda_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with at least one parents SDA S'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_non_sda_count_K',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with non-SDA parents K'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_non_sda_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with non-SDA parents S'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_sda_count_K',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with at least one parents SDA K'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_sda_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with at least one parents SDA S'),
        ),
    ]
