# Generated by Django 3.2.6 on 2024-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0109_opening_opening_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttype',
            options={'ordering': ['order_number']},
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='boarding_boy_count',
            new_name='boarding_boy_count_E',
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='boarding_girl_count',
            new_name='boarding_boy_count_S',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_0_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_10_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_11_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_12_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_1_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_2_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_3_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_4_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_5_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_6_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_7_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_8_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_grade_9_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_k_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_pre_k_end_count',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='previous_year_withdraw_count',
        ),
        migrations.AddField(
            model_name='opening',
            name='boarding_girl_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='boarding_girl_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
