# Generated by Django 3.2.6 on 2024-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0110_auto_20240625_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='day_boy_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='day_boy_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='day_girl_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='day_girl_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
