# Generated by Django 3.2.6 on 2024-06-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0112_auto_20240625_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
