# Generated by Django 3.2.6 on 2024-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0113_alter_degree_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
