# Generated by Django 3.2.6 on 2024-06-26 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0114_personnel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='annual_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='reporting.annualreport'),
        ),
    ]
