# Generated by Django 3.2.6 on 2024-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0117_opening_grade_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecount',
            name='grade_0_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='0'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_10_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_11_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_12_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_1_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_2_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_3_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_4_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_5_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_6_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_7_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_8_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_9_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='k_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='pre_k_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pre-K'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='associate_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Associate'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='bachelor_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bachelor'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='boarding_boy_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Boys E'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='boarding_boy_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Boys S'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='boarding_girl_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Girls E'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='boarding_girl_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Girls S'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='boy_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boys'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='day_boy_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Boys E'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='day_boy_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Boys S'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='day_girl_count_E',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Girls E'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='day_girl_count_S',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Girls S'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='did_not_return_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Did Not Return'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='doctorate_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Doctorate'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='general_staff_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='General Staff'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='girl_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Girls'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='graduated_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduated'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='masters_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Masters'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='non_sda_teacher_admin_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='non-SDA Administrative and Teaching Staff'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='professional_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Professional'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='teacher_admin_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Administrative and Teaching Staff'),
        ),
    ]
