# Generated by Django 3.2.6 on 2024-06-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0118_auto_20240626_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closing',
            old_name='withdrew_count',
            new_name='withdraw_count',
        ),
    ]
