# Generated by Django 3.2.6 on 2024-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0121_alter_closing_grade_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='final_school_day',
            field=models.DateField(blank=True, null=True, verbose_name='Final date school was in full session (last academic school day)'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='student_evangelistic_meetings_baptism',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total number of baptisms as a result of student evangelism'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('B', 'Bible'), ('C', 'Computer/Tech'), ('F', 'Fine Arts'), ('L', 'Language Arts'), ('M', 'Math'), ('ML', 'Modern Language'), ('SC', 'Science'), ('SS', 'Social Studies'), ('V', 'Vocational Arts Courses'), ('W', 'Wellness/Health/PE'), ('E', 'Elementary')], max_length=50),
        ),
    ]
