# Generated by Django 3.2.6 on 2024-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0124_testmaterialordered_testmaterialtype_testorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='school',
        ),
        migrations.DeleteModel(
            name='TestMaterialOrdered',
        ),
        migrations.DeleteModel(
            name='TestMaterialType',
        ),
        migrations.DeleteModel(
            name='TestOrder',
        ),
    ]
