# Generated by Django 3.2 on 2024-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0126_alter_annualreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('part-time', 'Part Time'), ('graduated', 'Graduated'), ('did_not_return', 'Did Not Return'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=15),
        ),
    ]
