# Generated by Django 3.2 on 2024-07-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0127_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeGradeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_k_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pre-K')),
                ('k_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='K')),
                ('grade_0_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='0')),
                ('grade_1_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='1')),
                ('grade_2_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='2')),
                ('grade_3_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='3')),
                ('grade_4_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='4')),
                ('grade_5_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='5')),
                ('grade_6_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='6')),
                ('grade_7_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='7')),
                ('grade_8_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='8')),
                ('grade_9_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='9')),
                ('grade_10_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='10')),
                ('grade_11_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='11')),
                ('grade_12_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='12')),
            ],
        ),
        migrations.AddField(
            model_name='opening',
            name='part_time_grade_count',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='reporting.parttimegradecount'),
        ),
    ]
