# Generated by Django 3.2 on 2024-07-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0128_auto_20240722_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='new_student_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
