# Generated by Django 3.2 on 2024-07-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0129_closing_new_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='part_time_grade_count',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing', to='reporting.parttimegradecount'),
        ),
    ]
