# Generated by Django 3.2 on 2024-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0130_closing_part_time_grade_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='no_mission_trips',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Mission trips your students participated in, not organized by the school'),
        ),
    ]
