# Generated by Django 3.2 on 2024-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0131_alter_closing_no_mission_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='outreach',
            field=models.TextField(blank=True, null=True, verbose_name='Other Outreach Activities'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='no_mission_trips',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not organized by the school'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='no_mission_trips_school',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Planned or executed by your school'),
        ),
    ]
