# Generated by Django 3.2 on 2024-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0132_auto_20240723_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inservicediscretionarydays',
            name='type',
            field=models.CharField(choices=[('CI', 'Curriculum Improvement'), ('II', 'Instructional Improvement'), ('CM', 'Classroom Management'), ('IS', 'ISEI Workshop'), ('TE', 'Teacher/Administrator Evaluation'), ('TC', 'Teacher Convention'), ('OT', 'Other'), ('DS', 'Discretionary')], max_length=2),
        ),
    ]
