# Generated by Django 3.2 on 2024-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0133_alter_inservicediscretionarydays_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='day190',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='School_calendars'),
        ),
    ]
