# Generated by Django 3.2 on 2024-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0134_day190_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='personnel',
            name='years_work_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years Work Experience'),
        ),
    ]
