# Generated by Django 3.2 on 2024-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0135_auto_20240725_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='years_administrative_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of Administrative Experience'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='years_teaching_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of Teaching Experience'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='years_work_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of Work Experience'),
        ),
    ]
