# Generated by Django 3.2 on 2024-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0136_auto_20240725_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='baptized',
            field=models.CharField(choices=[('Y', 'Yes, SDA'), ('O', 'Yes, non-SDA'), ('N', 'No'), ('U', '-')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_sda',
            field=models.CharField(choices=[('Y', 'Yes, SDA'), ('O', 'Yes, non-SDA'), ('N', 'No'), ('U', '-')], default='U', max_length=1, verbose_name='Parent SDA'),
        ),
    ]
