# Generated by Django 3.2 on 2024-08-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0137_auto_20240728_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorthyStudentScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_enrollment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Opening Enrollment (9-12th grade)')),
                ('closing_enrollment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Closing Enrollment (9-12th grade)')),
                ('school_generated_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Academy Generated Worthy Student Fund distributed')),
                ('wss_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Worthy Student Scholarship Fund money distributed')),
                ('students_assisted_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of students assisted from ALL funds')),
                ('students_assisted_wss', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of students assisted from Worthy Student Scholarship Fund')),
                ('next_year_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount of academy generated worthy student money budgeted for next year')),
                ('annual_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worthy_student', to='reporting.annualreport')),
            ],
        ),
    ]
