# Generated by Django 3.2 on 2024-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0138_worthystudentscholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='worthystudentscholarship',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='wss_letters/%Y', verbose_name='Thank you letter'),
        ),
    ]
