# Generated by Django 3.2 on 2024-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0139_worthystudentscholarship_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='baptized_non_sda_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with non-SDA count'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unknown_baptismal_statut_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Unknown baptismal status'),
        ),
    ]
