# Generated by Django 3.2 on 2024-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0140_auto_20240826_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffposition',
            name='teaching_position',
            field=models.BooleanField(default=False),
        ),
    ]
