# Generated by Django 3.2 on 2024-09-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_auto_20240908_2022'),
        ('reporting', '0141_staffposition_teaching_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
    ]
