# Generated by Django 3.2 on 2024-09-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0143_alter_personnel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='day190',
            name='calendar_link',
            field=models.URLField(blank=True, null=True, verbose_name='School Calendar Link'),
        ),
        migrations.AlterField(
            model_name='day190',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='School_calendars', verbose_name='School Calendar'),
        ),
    ]
