# Generated by Django 3.2 on 2025-01-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0145_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttype',
            name='isei_created',
        ),
    ]
