# Generated by Django 3.2 on 2025-02-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0129_alter_academicclass_name'),
        ('users', '0120_school_board_chair'),
        ('reporting', '0146_remove_reporttype_isei_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongitudinalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='users.school')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='teachercert.schoolyear')),
            ],
            options={
                'unique_together': {('school', 'year', 'grade')},
            },
        ),
    ]
