# Generated by Django 3.2 on 2025-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0147_longitudinalenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='School_calendars/%Y', verbose_name='School Calendar/%Y'),
        ),
    ]
