# Generated by Django 5.2 on 2025-04-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0148_alter_day190_file'),
        ('users', '0127_migrate_address_to_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSpecificReportDueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('opening_report', models.BooleanField(default=False)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reporttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
    ]
