# Generated by Django 5.2 on 2025-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0149_schoolspecificreportduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(choices=[(-2, 'Pre-K'), (-1, 'K'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, 'Graduated'), (14, 'GA-I'), (15, 'GA-II'), (16, 'GA-III')]),
        ),
    ]
