# Generated by Django 5.2 on 2025-04-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0150_alter_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecount',
            name='ga_i_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-I'),
        ),
        migrations.AddField(
            model_name='gradecount',
            name='ga_ii_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-II'),
        ),
        migrations.AddField(
            model_name='gradecount',
            name='ga_iii_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-III'),
        ),
        migrations.AddField(
            model_name='parttimegradecount',
            name='ga_i_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-I'),
        ),
        migrations.AddField(
            model_name='parttimegradecount',
            name='ga_ii_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-II'),
        ),
        migrations.AddField(
            model_name='parttimegradecount',
            name='ga_iii_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GA-III'),
        ),
    ]
