# Generated by Django 5.2 on 2025-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0152_alter_gradecount_ga_i_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_non_sda_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with non-SDA parents GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='baptized_parent_sda_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baptised with at least one parents SDA GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='boarding_boy_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Boys GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='boarding_girl_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Boarding Girls GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='day_boy_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Boys GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='day_girl_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day Girl GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_non_sda_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with non-SDA parents GA'),
        ),
        migrations.AddField(
            model_name='opening',
            name='unbaptized_parent_sda_count_GA',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Not baptised with at least one parents SDA GA'),
        ),
    ]
