# Generated by Django 5.2 on 2025-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0155_alter_longitudinalenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longitudinalenrollment',
            name='grade',
            field=models.IntegerField(choices=[('Pre-K', -2), ('K', -1), ('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('Graduated', 13), ('GA-I', 14), ('GA-II', 15), ('GA-III', 16)]),
        ),
    ]
