# Generated by Django 5.2 on 2025-05-22 07:39

import ISEIapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0156_alter_longitudinalenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worthystudentscholarship',
            name='letter',
            field=models.FileField(blank=True, null=True, storage=ISEIapp.storage_backends.MediaStorage(), upload_to='wss_letters/%Y', verbose_name='Thank you letter'),
        ),
    ]
