# Generated by Django 5.2 on 2025-05-22 07:53

import ISEIapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0157_alter_worthystudentscholarship_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day190',
            name='file',
            field=models.FileField(blank=True, null=True, storage=ISEIapp.storage_backends.MediaStorage(), upload_to='School_calendars/%Y', verbose_name='School Calendar/%Y'),
        ),
    ]
