# Generated by Django 5.2 on 2025-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0158_alter_day190_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='day190',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
