# Generated by Django 5.2 on 2025-08-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0159_day190_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
