# Generated by Django 5.2 on 2025-10-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0160_alter_student_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inservicediscretionarydays',
            name='type',
            field=models.CharField(choices=[('CI', 'Curriculum Improvement'), ('II', 'Instructional Improvement'), ('CM', 'Classroom Management'), ('IS', 'ISEI Workshop'), ('TC', 'Teacher Convention'), ('OT', 'Other'), ('DS', 'Discretionary')], max_length=2),
        ),
    ]
