# Generated by Django 5.2 on 2026-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0161_alter_inservicediscretionarydays_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradecount',
            name='ga_i_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-I'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='ga_ii_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-II'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='ga_iii_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-III'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_0_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='0'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_10_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_11_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_12_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_1_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_2_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_3_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_4_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_5_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_6_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_7_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_8_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='grade_9_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='k_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='gradecount',
            name='pre_k_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Pre-K'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='ga_i_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-I'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='ga_ii_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-II'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='ga_iii_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='GA-III'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_0_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='0'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_10_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_11_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_12_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_1_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_2_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_3_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_4_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_5_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_6_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_7_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_8_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='grade_9_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='k_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='parttimegradecount',
            name='pre_k_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Pre-K'),
        ),
    ]
