# Generated by Django 5.2 on 2026-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0163_alter_gradecount_ga_i_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longitudinalenrollment',
            name='enrollment_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
