# Generated by Django 5.2 on 2026-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0164_alter_longitudinalenrollment_enrollment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worthystudentscholarship',
            name='school_generated_fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Non MWF Worthy Student Fund distributed'),
        ),
        migrations.AlterField(
            model_name='worthystudentscholarship',
            name='students_assisted_wss',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of students assisted from MWF Worthy Student Scholarship Fund'),
        ),
        migrations.AlterField(
            model_name='worthystudentscholarship',
            name='wss_fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='MWF Worthy Student Scholarship Fund distributed'),
        ),
    ]
