# Generated by Django 5.2 on 2026-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0165_alter_worthystudentscholarship_school_generated_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
