# Generated by Django 5.2 on 2026-08-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0166_alter_student_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('part-time', 'Part Time'), ('accepted', 'Accepted'), ('graduated', 'Graduated'), ('did_not_return', 'Did Not Return'), ('withdrawn', 'Withdrawn'), ('no-show', 'No Show')], default='enrolled', max_length=15),
        ),
    ]
