# Generated by Django 3.2 on 2021-06-30 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDAType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe the possible activities', max_length=100)),
                ('evidence', models.CharField(help_text='What kind of evidence is expected for this type of activity', max_length=50, null=True)),
                ('category', models.CharField(choices=[('i', 'Independent'), ('g', 'Group'), ('c', 'Collaboration'), ('p', 'Presentation & Writing')], help_text='Choose a category', max_length=1)),
                ('ceu_value', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('active_year', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='PDARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('principal_reviewed', models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1)),
                ('principal_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('isei_approved', models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1)),
                ('isei_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, help_text='Summarize what you have learned from the combined activities and how you plan to apply this learning to your classroom', max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachercert.schoolyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher')),
            ],
            options={
                'ordering': ['school_year'],
                'unique_together': {('teacher', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='PDAInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('description', models.CharField(max_length=3000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('ceu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clock_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pages', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Supporting_Files/%Y/%m/%d')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('submitted', models.BooleanField(blank=True, default=False)),
                ('principal_signed', models.BooleanField(blank=True, default=False)),
                ('isei_reviewed', models.BooleanField(blank=True, default=False)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('approved_ceu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approval_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('pda_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdarecord')),
                ('pda_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdatype')),
            ],
            options={
                'ordering': ['pda_record'],
            },
        ),
    ]
