# Generated by Django 3.2 on 2021-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdatype',
            old_name='type',
            new_name='description',
        ),
        migrations.AddField(
            model_name='pdatype',
            name='evidence',
            field=models.CharField(help_text='What kind of evidence is expected for this type of activity', max_length=25, null=True),
        ),
    ]
