# Generated by Django 3.2 on 2021-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0002_auto_20210510_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdatype',
            name='evidence',
            field=models.CharField(help_text='What kind of evidence is expected for this type of activity', max_length=50, null=True),
        ),
    ]
