# Generated by Django 3.2 on 2021-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0003_alter_pdatype_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Supporting_Files/'),
        ),
    ]
