# Generated by Django 3.2 on 2021-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0003_rename_isei_approved_pdarecord_isei_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdainstance',
            old_name='approval_comment',
            new_name='isei_comment',
        ),
        migrations.RemoveField(
            model_name='pdainstance',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='pdainstance',
            name='principal_signed',
        ),
        migrations.RemoveField(
            model_name='pdainstance',
            name='submitted',
        ),
        migrations.AddField(
            model_name='pdainstance',
            name='principal_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pdainstance',
            name='principal_reviewed',
            field=models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='pdainstance',
            name='isei_reviewed',
            field=models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1),
        ),
    ]
