# Generated by Django 3.2 on 2021-07-02 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0004_auto_20210701_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdarecord',
            name='summary',
            field=models.CharField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
