# Generated by Django 3.2 on 2021-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0005_alter_pdarecord_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdarecord',
            name='isei_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pdarecord',
            name='principal_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
