# Generated by Django 3.2 on 2021-07-02 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0006_auto_20210702_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdarecord',
            name='isei_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pdarecord',
            name='principal_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pdarecord',
            name='summary',
            field=models.CharField(blank=True, max_length=6000, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
