# Generated by Django 3.2 on 2021-07-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0007_auto_20210702_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdainstance',
            old_name='date_submitted',
            new_name='date_resubmitted',
        ),
    ]
