# Generated by Django 3.2 on 2021-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0008_rename_date_submitted_pdainstance_date_resubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdarecord',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdarecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
