# Generated by Django 3.2 on 2021-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0009_auto_20210705_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='date_completed',
            field=models.DateField(help_text='mm/dd/yyyy or yyyy-mm-dd'),
        ),
    ]
