# Generated by Django 3.2 on 2021-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0010_alter_pdainstance_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdarecord',
            name='date_submitted',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy or yyyy-mm-dd', null=True),
        ),
    ]
