# Generated by Django 3.2 on 2021-07-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0011_alter_pdarecord_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='date_completed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pdarecord',
            name='date_submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
