# Generated by Django 3.2 on 2021-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0012_auto_20210708_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdatype',
            name='evidence',
            field=models.CharField(blank=True, help_text='What kind of evidence is expected for this type of activity', max_length=50, null=True),
        ),
    ]
