# Generated by Django 3.2 on 2021-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0013_alter_pdatype_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdainstance',
            name='ceu',
        ),
        migrations.RemoveField(
            model_name='pdainstance',
            name='pages',
        ),
        migrations.AddField(
            model_name='pdainstance',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='pdainstance',
            name='units',
            field=models.CharField(choices=[('c', 'CEUs'), ('h', 'Clock Hours'), ('d', 'Days'), ('p', 'Pages')], default='c', max_length=1),
        ),
    ]
