# Generated by Django 3.2 on 2021-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0015_auto_20210709_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
