# Generated by Django 3.2 on 2021-07-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210714_0838'),
        ('teachercert', '0016_alter_pdainstance_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDARecord',
            new_name='PDAReport',
        ),
        migrations.AlterModelOptions(
            name='pdainstance',
            options={'ordering': ['pda_report']},
        ),
        migrations.RenameField(
            model_name='pdainstance',
            old_name='pda_record',
            new_name='pda_report',
        ),
    ]
