# Generated by Django 3.2 on 2021-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0017_auto_20210714_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdatype',
            name='max_cap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
