# Generated by Django 3.2 on 2021-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0018_pdatype_max_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdareport',
            name='academic_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdareport',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pdareport',
            name='university',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
