# Generated by Django 3.2 on 2021-07-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0019_auto_20210716_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdareport',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='pdareport',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='pdareport',
            name='university',
        ),
        migrations.CreateModel(
            name='academic_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('date_completed', models.DateField()),
                ('transcript_requested', models.BooleanField(default=False)),
                ('transcript_received', models.BooleanField(default=False)),
                ('pda_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdareport')),
            ],
        ),
    ]
