# Generated by Django 3.2 on 2021-07-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0020_auto_20210720_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='academic_class',
            new_name='AcademicClass',
        ),
    ]
