# Generated by Django 3.2 on 2021-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0021_rename_academic_class_academicclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pdatype',
            options={'ordering': ('category',)},
        ),
    ]
