# Generated by Django 3.2 on 2021-07-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0022_auto_20210721_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdainstance',
            name='reviewed_at',
            field=models.DateField(blank=True, default='2020-05-02', null=True),
        ),
        migrations.AddField(
            model_name='pdareport',
            name='reviewed_at',
            field=models.DateField(blank=True, default='2020-05-02', null=True),
        ),
    ]
