# Generated by Django 3.2 on 2021-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0024_auto_20210721_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdainstance',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
