# Generated by Django 3.2 on 2021-07-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210714_0838'),
        ('teachercert', '0025_auto_20210722_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.certificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.certificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.certificationtype')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher')),
            ],
        ),
    ]
