# Generated by Django 3.2 on 2021-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0026_certification_certificationtype_renewal_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certification_type',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_type',
            field=models.ManyToManyField(to='teachercert.CertificationType'),
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='certification_type',
        ),
        migrations.AddField(
            model_name='renewal',
            name='certification_type',
            field=models.ManyToManyField(to='teachercert.CertificationType'),
        ),
    ]
