# Generated by Django 3.2 on 2021-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0027_auto_20210729_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
