# Generated by Django 3.2 on 2021-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0028_alter_certificationtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
