# Generated by Django 3.2 on 2021-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0029_alter_certificationtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
