# Generated by Django 3.2 on 2021-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0030_alter_certificationtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationtype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
