# Generated by Django 3.2 on 2021-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0031_alter_certificationtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='category',
            field=models.CharField(choices=[('g', 'General'), ('b', 'Basic'), ('o', 'Other')], default='g', help_text='Choose a category', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='certification_type',
        ),
        migrations.AddField(
            model_name='requirement',
            name='certification_type',
            field=models.ManyToManyField(to='teachercert.CertificationType'),
        ),
    ]
