# Generated by Django 3.2 on 2021-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0032_auto_20210730_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
