# Generated by Django 3.2 on 2021-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0033_alter_requirement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
