# Generated by Django 3.2 on 2021-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0034_alter_requirement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
