# Generated by Django 3.2 on 2021-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0035_alter_requirement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
