# Generated by Django 3.2 on 2021-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0036_alter_requirement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
