# Generated by Django 3.2 on 2021-07-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0037_renewal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationtype',
            name='years_valid',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
