# Generated by Django 3.2 on 2021-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0038_certificationtype_years_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
