# Generated by Django 3.2 on 2021-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0039_alter_renewal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementaryMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endorsments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
