# Generated by Django 3.2 on 2021-07-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0040_elementarymethods_endorsments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElementaryMethods',
            new_name='ElementaryMethod',
        ),
        migrations.RenameModel(
            old_name='Endorsments',
            new_name='Endorsement',
        ),
    ]
