# Generated by Django 3.2 on 2021-07-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0043_auto_20210730_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='EmailMessages',
        ),
    ]
