# Generated by Django 3.2 on 2021-07-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0045_rename_requirements_requirement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Requirement',
        ),
    ]
