# Generated by Django 3.2 on 2021-07-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0047_rename_emailmessages_emailmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
