# Generated by Django 3.2 on 2021-08-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_teacher_date_of_birth'),
        ('teachercert', '0049_emailmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='TCertificate',
        ),
        migrations.RenameModel(
            old_name='TeacherEndorsement',
            new_name='TEndorsement',
        ),
    ]
