# Generated by Django 3.2 on 2021-08-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0050_auto_20210801_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendorsement',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachercert.tcertificate'),
        ),
    ]
