# Generated by Django 3.2 on 2021-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_teacher_options'),
        ('teachercert', '0051_alter_tendorsement_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcertificate',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='tcertificate',
            unique_together={('teacher', 'certification_type', 'issue_date')},
        ),
    ]
