# Generated by Django 3.2 on 2021-08-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0052_auto_20210812_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
