# Generated by Django 3.2 on 2021-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210813_1448'),
        ('teachercert', '0053_auto_20210813_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='country',
            field=models.ManyToManyField(to='users.Country'),
        ),
    ]
