# Generated by Django 3.2 on 2021-08-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0054_schoolyear_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclass',
            name='pda_report',
        ),
    ]
