# Generated by Django 3.2 on 2021-08-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210813_1448'),
        ('teachercert', '0055_remove_academicclass_pda_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
            preserve_default=False,
        ),
    ]
