# Generated by Django 3.2 on 2021-08-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0056_academicclass_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicclass',
            old_name='class_name',
            new_name='name',
        ),
    ]
