# Generated by Django 3.2 on 2021-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0057_rename_class_name_academicclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcertificate',
            name='note_isei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tcertificate',
            name='note_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
