# Generated by Django 3.2 on 2021-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0059_auto_20210817_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
