# Generated by Django 3.2 on 2021-08-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_delete_teachercertificationapplication'),
        ('teachercert', '0061_alter_tcertificate_renewal_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCertificationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField(default=True)),
                ('cert_level', models.CharField(blank=True, choices=[('v', 'Vocational'), ('s', 'Secondary'), ('e', 'Elementary'), ('d', 'Designated')], max_length=1, null=True, verbose_name='Certification Level Requested')),
                ('endors_level', models.CharField(blank=True, choices=[('e', 'Elementary'), ('s', 'Secondary Subject Area(s)')], max_length=1, null=True, verbose_name='Endorsement Level Requested')),
                ('subject_areas', models.CharField(blank=True, max_length=50, verbose_name='Subject Areas')),
                ('resume', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='a', max_length=1, verbose_name='Resume of work/teaching experience is included (for Designated and Vocational)')),
                ('principal_letter', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('a', 'N/A')], default='a', max_length=1, verbose_name='Letter of Recommendation from Principal has been sent (for Designated and Vocational)')),
                ('felony', models.BooleanField(default=False, verbose_name='Have you ever been convicted of a felony (including a suspended sentence)?')),
                ('felony_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='If yes, please describe')),
                ('sexual_offence', models.BooleanField(default=False, verbose_name='Have you ever been under investigation for any sexual offense (excluding any charges which were fully cleared)?')),
                ('sexual_offence_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='If yes, please describe')),
                ('signature', models.CharField(max_length=50, verbose_name="Applicant's signature")),
                ('date', models.DateField()),
                ('date_received', models.DateField(auto_now_add=True, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('public_note', models.CharField(blank=True, max_length=255, null=True)),
                ('isei_note', models.CharField(blank=True, max_length=255, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
