# Generated by Django 3.2 on 2021-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0062_teachercertificationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='isei_revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
