# Generated by Django 3.2.6 on 2021-08-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0065_auto_20210824_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercertificationapplication',
            name='subject_areas',
        ),
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='courses_taught',
            field=models.CharField(blank=True, max_length=50, verbose_name='Courses Taught'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='endors_level',
            field=models.CharField(blank=True, choices=[('e', 'Elementary'), ('s', 'Secondary Area(s)')], max_length=1, null=True, verbose_name='Endorsement Level Requested'),
        ),
    ]
