# Generated by Django 3.2.6 on 2021-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0066_auto_20210824_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='principal_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='Applications/Principal Letters/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='Applications/Resumes/%Y/%m/%d'),
        ),
    ]
