# Generated by Django 3.2.6 on 2021-08-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0067_auto_20210824_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='felony',
            field=models.BooleanField(default=False, verbose_name='Check if you have ever been convicted of a felony (including a suspended sentence)?'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='sexual_offence',
            field=models.BooleanField(default=False, verbose_name='Check if you have ever been under investigation for any sexual offense (excluding any charges which were fully cleared).'),
        ),
    ]
