# Generated by Django 3.2.6 on 2021-08-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0068_auto_20210824_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='felony',
            field=models.BooleanField(default=False, verbose_name='Check if you have ever been convicted of a felony (including a suspended sentence).'),
        ),
    ]
