# Generated by Django 3.2.6 on 2021-08-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0069_alter_teachercertificationapplication_felony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercertificationapplication',
            name='principal_letter',
        ),
        migrations.RemoveField(
            model_name='teachercertificationapplication',
            name='resume',
        ),
    ]
