# Generated by Django 3.2.6 on 2021-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0070_auto_20210825_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdatype',
            name='evidence',
            field=models.CharField(blank=True, help_text='What kind of evidence is expected for this type of activity', max_length=100, null=True),
        ),
    ]
