# Generated by Django 3.2.6 on 2021-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0071_alter_pdatype_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdainstance',
            name='evidence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
