# Generated by Django 3.2.6 on 2021-08-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0072_pdainstance_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDACategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='pdatype',
            name='category',
            field=models.CharField(blank=True, help_text='Choose a category', max_length=1, null=True),
        ),
    ]
