# Generated by Django 3.2.6 on 2021-08-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0073_auto_20210825_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDACategories',
            new_name='PDACategory',
        ),
    ]
