# Generated by Django 3.2.6 on 2021-08-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0074_rename_pdacategories_pdacategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdatype',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose a category', null=True, on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdacategory'),
        ),
    ]
