# Generated by Django 3.2.6 on 2021-08-25 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0075_alter_pdatype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdainstance',
            name='pda_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdacategory'),
        ),
    ]
