# Generated by Django 3.2.6 on 2021-08-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0076_pdainstance_pda_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdatype',
            name='category',
            field=models.ForeignKey(default=1, help_text='Choose a category', on_delete=django.db.models.deletion.PROTECT, to='teachercert.pdacategory'),
            preserve_default=False,
        ),
    ]
