# Generated by Django 3.2.6 on 2021-08-25 22:29

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0078_rename_pda_category_pdainstance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdainstance',
            name='pda_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='teachercert.pdatype'),
        ),
    ]
