# Generated by Django 3.2.6 on 2021-08-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0080_auto_20210825_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdatype',
            options={'ordering': ('pda_category',)},
        ),
        migrations.RenameField(
            model_name='pdatype',
            old_name='category',
            new_name='pda_category',
        ),
    ]
