# Generated by Django 3.2.6 on 2021-08-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_teacher_joined_at'),
        ('teachercert', '0081_auto_20210827_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDAReport',
            new_name='CEUReport',
        ),
    ]
