# Generated by Django 3.2.6 on 2021-08-30 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0082_rename_pdareport_ceureport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEUInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField()),
                ('description', models.CharField(max_length=3000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('units', models.CharField(choices=[('c', 'CEUs'), ('h', 'Clock Hours'), ('d', 'Days'), ('p', 'Pages')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('evidence', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Supporting_Files/%Y/%m/%d')),
                ('date_resubmitted', models.DateField(blank=True, null=True)),
                ('principal_reviewed', models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1)),
                ('principal_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('isei_reviewed', models.CharField(choices=[('n', 'Not yet reviewed'), ('a', 'Approved'), ('d', 'Denied')], default='n', max_length=1)),
                ('isei_comment', models.CharField(blank=True, max_length=300, null=True)),
                ('approved_ceu', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['ceu_report'],
            },
        ),
        migrations.CreateModel(
            name='CEUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe the possible activities', max_length=100)),
                ('evidence', models.CharField(blank=True, help_text='What kind of evidence is expected for this type of activity', max_length=100, null=True)),
                ('ceu_value', models.CharField(blank=True, max_length=60, null=True)),
                ('max_cap', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('ceu_category',),
            },
        ),
        migrations.RemoveField(
            model_name='pdatype',
            name='pda_category',
        ),
        migrations.RenameModel(
            old_name='PDACategory',
            new_name='CEUCategory',
        ),
        migrations.DeleteModel(
            name='PDAInstance',
        ),
        migrations.DeleteModel(
            name='PDAType',
        ),
        migrations.AddField(
            model_name='ceutype',
            name='ceu_category',
            field=models.ForeignKey(help_text='Choose a category', on_delete=django.db.models.deletion.PROTECT, to='teachercert.ceucategory'),
        ),
        migrations.AddField(
            model_name='ceuinstance',
            name='ceu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teachercert.ceucategory'),
        ),
        migrations.AddField(
            model_name='ceuinstance',
            name='ceu_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.ceureport'),
        ),
        migrations.AddField(
            model_name='ceuinstance',
            name='ceu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachercert.ceutype'),
        ),
    ]
