# Generated by Django 3.2.6 on 2021-09-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_teacher_options'),
        ('teachercert', '0085_rename_teacherbasicrequirements_teacherbasicrequirement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherbasicrequirement',
            unique_together={('teacher', 'basic_requirement')},
        ),
    ]
