# Generated by Django 3.2.6 on 2021-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0087_auto_20210901_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercertificationapplication',
            name='date_initial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
