# Generated by Django 3.2.6 on 2021-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0090_teacherbasicrequirement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbasicrequirement',
            name='course',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
