# Generated by Django 3.2.6 on 2021-09-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0091_alter_teacherbasicrequirement_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicclass',
            options={'ordering': ('-date_completed',)},
        ),
        migrations.AlterModelOptions(
            name='elementarymethod',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='endorsement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tcertificate',
            options={'ordering': ('renewal_date',)},
        ),
        migrations.AlterModelOptions(
            name='teachercertificationapplication',
            options={'ordering': ('date',)},
        ),
    ]
