# Generated by Django 3.2.6 on 2021-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0092_auto_20210906_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcertificate',
            name='nad',
            field=models.BooleanField(default=False),
        ),
    ]
