# Generated by Django 3.2.6 on 2021-09-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0093_tcertificate_nad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercertificationapplication',
            options={'ordering': ('billed', 'closed', 'date')},
        ),
    ]
