# Generated by Django 3.2.6 on 2021-09-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0094_alter_teachercertificationapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendorsement',
            name='range',
            field=models.CharField(blank=True, default='9-12', max_length=5, null=True),
        ),
    ]
