# Generated by Django 3.2.6 on 2021-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0096_auto_20210915_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='endors_level',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Grade Range Requested'),
        ),
    ]
