# Generated by Django 3.2.6 on 2021-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0097_alter_teachercertificationapplication_endors_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcertificate',
            name='public_note',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
