# Generated by Django 3.2.6 on 2021-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0099_alter_tcertificate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='receiver',
            field=models.CharField(default='ISEI', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sender',
            field=models.CharField(default='Teacher', max_length=10),
            preserve_default=False,
        ),
    ]
