# Generated by Django 3.2.6 on 2021-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0101_auto_20211116_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
