# Generated by Django 3.2.6 on 2021-11-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0103_auto_20211116_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='EmailMessageTemplate',
        ),
    ]
