# Generated by Django 3.2.6 on 2021-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0104_rename_emailmessage_emailmessagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='billed',
            field=models.CharField(choices=[('y', 'Billed'), ('n', 'Not Billed'), ('a', 'N/A')], default='y', max_length=1),
        ),
    ]
