# Generated by Django 3.2.6 on 2021-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0106_alter_teachercertificationapplication_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='billed',
            field=models.CharField(choices=[('y', 'Billed'), ('n', 'Not Billed'), ('z', 'N/A')], default='n', max_length=1),
        ),
    ]
