# Generated by Django 3.2.6 on 2021-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0108_alter_ceuinstance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceucategory',
            name='name',
            field=models.CharField(max_length=25, verbose_name='CEU Category'),
        ),
        migrations.AlterField(
            model_name='ceutype',
            name='description',
            field=models.CharField(help_text='Describe the possible activities', max_length=100, verbose_name='CEU Type'),
        ),
    ]
