# Generated by Django 3.2.6 on 2022-04-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0109_auto_20211210_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherbasicrequirement',
            name='basic_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachercert.requirement'),
        ),
    ]
