# Generated by Django 3.2.6 on 2022-04-27 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_teacher_background_check'),
        ('teachercert', '0110_alter_teacherbasicrequirement_basic_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sda', models.BooleanField(default=True, verbose_name='Member of SDA Church')),
                ('background_check', models.BooleanField(default=False, verbose_name='Clean background check')),
                ('ba_degree', models.BooleanField(verbose_name='Baccalaureate degree or higher')),
                ('experience', models.BooleanField(verbose_name='3-years teaching experience')),
                ('sop', models.BooleanField(verbose_name='Spirit of Prophecy')),
                ('sda_doctrine', models.BooleanField(verbose_name='SDA Doctrines')),
                ('sda_history', models.BooleanField(verbose_name='SDA Church History')),
                ('sda_health', models.BooleanField(verbose_name='SDA Health Principles')),
                ('sda_education', models.PositiveSmallIntegerField(verbose_name='Principles and Philosophy of SDA Education')),
                ('psychology', models.PositiveSmallIntegerField(verbose_name='Developmental and Educational Psychology')),
                ('assessment', models.PositiveSmallIntegerField(verbose_name='Educational Assessment')),
                ('exceptional_child', models.PositiveSmallIntegerField(verbose_name='Exceptional Child in the Classroom')),
                ('technology', models.PositiveSmallIntegerField(verbose_name='Technology in Teaching & Learning')),
                ('sec_methods', models.PositiveSmallIntegerField(verbose_name='Secondary Curriculum and Methods')),
                ('sec_rw_methods', models.PositiveSmallIntegerField(verbose_name='Secondary Reaching and Writing Methods (recommended) ')),
                ('endorsement_credits18', models.BooleanField(verbose_name='18-semester credits in endorsement area(s)')),
                ('em_science', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Science')),
                ('em_math', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Mathematics')),
                ('em_reading', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Reading')),
                ('em_language', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Language Arts')),
                ('em_religion', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Religion')),
                ('em_social', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Social Studies (recommended)')),
                ('em_health', models.PositiveSmallIntegerField(verbose_name='Elementary Methods in Health (recommended')),
                ('other_ed_credit', models.PositiveSmallIntegerField(verbose_name='Other Professional Education Credits')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
