# Generated by Django 3.2.6 on 2022-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0113_auto_20220427_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='no_Ds',
            field=models.BooleanField(default=False, verbose_name='No Grades below C-'),
            preserve_default=False,
        ),
    ]
