# Generated by Django 3.2.6 on 2022-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0114_standardchecklist_no_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardchecklist',
            name='endorsement_credits18',
            field=models.BooleanField(verbose_name='18 endorsment(s) credit'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='sda',
            field=models.BooleanField(default=True, verbose_name='SDA Church Member'),
        ),
    ]
