# Generated by Django 3.2.6 on 2022-05-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0115_auto_20220427_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardchecklist',
            name='endorsement_credits18',
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='credits12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12 credit subjects'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='credits18',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18 credit subjects'),
        ),
    ]
