# Generated by Django 3.2.6 on 2022-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0116_auto_20220513_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardchecklist',
            name='ba_degree',
            field=models.BooleanField(blank=True, null=True, verbose_name='Baccalaureate degree or higher'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='no_Ds',
            field=models.BooleanField(verbose_name='No Grades below C- for required classes'),
        ),
    ]
