# Generated by Django 3.2.6 on 2022-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0117_auto_20220515_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardchecklist',
            name='background_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Clean background check'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='3-years teaching experience'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='no_Ds',
            field=models.BooleanField(blank=True, null=True, verbose_name='No Grades below C- for required classes'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='sda_doctrine',
            field=models.BooleanField(default=False, verbose_name='SDA Doctrines'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='sda_health',
            field=models.BooleanField(default=False, verbose_name='SDA Health Principles'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='sda_history',
            field=models.BooleanField(default=False, verbose_name='SDA Church History'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='sop',
            field=models.BooleanField(default=False, verbose_name='Spirit of Prophecy'),
        ),
    ]
