# Generated by Django 3.2.6 on 2022-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0118_auto_20220515_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceureport',
            name='first_submitted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
