# Generated by Django 3.2.6 on 2022-08-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0120_rename_first_submitted_ceureport_last_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardchecklist',
            name='background_check',
        ),
    ]
