# Generated by Django 3.2.6 on 2022-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0121_remove_standardchecklist_background_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='dev_psychology',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Developmental Psychology (recommended)'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='psychology',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Educational Psychology'),
        ),
    ]
