# Generated by Django 3.2.6 on 2024-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0123_schoolyear_current_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
