# Generated by Django 3.2.6 on 2024-05-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0124_schoolyear_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='sequence',
            field=models.IntegerField(default=8, unique=True),
            preserve_default=False,
        ),
    ]
