# Generated by Django 3.2.6 on 2024-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0126_alter_ceuinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
