# Generated by Django 3.2.6 on 2024-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0104_school_current_school_year'),
        ('teachercert', '0127_alter_schoolyear_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='country',
            field=models.ManyToManyField(blank=True, to='users.Country'),
        ),
    ]
