# Generated by Django 3.2 on 2025-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0129_alter_academicclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceuinstance',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Supporting_Files/%Y'),
        ),
    ]
