# Generated by Django 3.2 on 2025-04-04 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0130_alter_ceuinstance_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceuinstance',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
