# Generated by Django 5.2 on 2025-05-22 07:53

import ISEIapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0131_alter_ceuinstance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceuinstance',
            name='file',
            field=models.FileField(blank=True, null=True, storage=ISEIapp.storage_backends.MediaStorage(), upload_to='Supporting_Files/%Y'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='principal_letter_file',
            field=models.FileField(blank=True, null=True, storage=ISEIapp.storage_backends.MediaStorage(), upload_to='Applications/Principal Letters/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teachercertificationapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, storage=ISEIapp.storage_backends.MediaStorage(), upload_to='Applications/Resumes/%Y/%m/%d'),
        ),
    ]
