# Generated by Django 5.2 on 2025-09-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0132_alter_ceuinstance_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='sda_doctrine_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='sda_education_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='sda_health_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='sda_history_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='sop_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
    ]
