# Generated by Django 5.2 on 2025-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0133_standardchecklist_sda_doctrine_ceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='technology_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
    ]
