# Generated by Django 5.2 on 2025-09-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0134_standardchecklist_technology_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='assessment_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='exceptional_child_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='psychology_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='credits12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12+ credit subjects'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='credits18',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18+ credit subjects'),
        ),
    ]
