# Generated by Django 5.2 on 2025-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0135_standardchecklist_assessment_ceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='sec_methods_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
        migrations.AddField(
            model_name='standardchecklist',
            name='sec_rw_methods_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
    ]
