# Generated by Django 5.2 on 2025-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0136_standardchecklist_sec_methods_ceu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='faith_integration_ceu',
            field=models.BooleanField(default=False, verbose_name='Faith Integration CEU'),
        ),
    ]
