# Generated by Django 5.2 on 2025-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0137_standardchecklist_faith_integration_ceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardchecklist',
            name='faith_integration',
            field=models.BooleanField(default=False, verbose_name='Fair Integration'),
        ),
        migrations.AlterField(
            model_name='standardchecklist',
            name='faith_integration_ceu',
            field=models.BooleanField(default=False, verbose_name='CEU'),
        ),
    ]
