# Generated by Django 5.2 on 2025-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0138_standardchecklist_faith_integration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardchecklist',
            name='faith_integration',
            field=models.BooleanField(default=False, verbose_name='Faith Integration'),
        ),
    ]
