# Generated by Django 5.2 on 2025-10-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0139_alter_standardchecklist_faith_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceuinstance',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
