# Generated by Django 5.2 on 2026-08-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachercert', '0140_ceuinstance_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceureport',
            name='isei_comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
