# Generated by Django 3.2 on 2024-12-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0003_rename_accreditationterms_accreditationterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationterm',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditationterm',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
