# Generated by Django 3.2 on 2024-12-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0004_auto_20241203_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation.accreditationterm'),
            preserve_default=False,
        ),
    ]
