# Generated by Django 3.2 on 2024-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0006_auto_20241204_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='visit_end_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accreditation',
            name='visit_start_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='current_accreditation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
