# Generated by Django 3.2 on 2024-12-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0007_auto_20241204_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='visit_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='visit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
