# Generated by Django 3.2 on 2024-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0009_indicator_schooltype_standard_suggestedevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Not Met'), (2, 'Partially Met'), (3, 'Met'), (4, 'Exceptional')])),
            ],
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='level',
        ),
        migrations.AddField(
            model_name='indicator',
            name='levels',
            field=models.ManyToManyField(to='accreditation.Level'),
        ),
    ]
