# Generated by Django 3.2 on 2024-12-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0011_auto_20241217_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.schooltype'),
        ),
    ]
