# Generated by Django 3.2 on 2024-12-17 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0012_level_school_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='school_type',
        ),
        migrations.AddField(
            model_name='indicator',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.schooltype'),
        ),
    ]
