# Generated by Django 3.2 on 2024-12-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0014_alter_indicator_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='key_word',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
