# Generated by Django 3.2 on 2024-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0015_indicator_key_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='key_word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
