# Generated by Django 3.2 on 2024-12-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0016_alter_indicator_key_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='evidence',
        ),
        migrations.AddField(
            model_name='standard',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
