# Generated by Django 3.2 on 2024-12-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0017_auto_20241218_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedEvidence',
        ),
    ]
