# Generated by Django 3.2 on 2024-12-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0018_delete_suggestedevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
