# Generated by Django 3.2 on 2024-12-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0019_alter_indicator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='coa_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
