# Generated by Django 3.2 on 2024-12-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0020_accreditation_coa_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='coa_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='COA Approval Date'),
        ),
    ]
