# Generated by Django 3.2 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0021_alter_accreditation_coa_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('standard', 'code', 'version')},
        ),
    ]
