# Generated by Django 3.2 on 2025-01-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0022_auto_20250109_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='parent_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substandards', to='accreditation.standard'),
        ),
    ]
