# Generated by Django 3.2 on 2025-01-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0023_standard_parent_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
