# Generated by Django 3.2 on 2025-01-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0027_auto_20250113_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.accreditationterm'),
        ),
    ]
