# Generated by Django 3.2 on 2025-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0028_alter_accreditation_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
