# Generated by Django 3.2 on 2025-01-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0029_auto_20250114_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accreditation',
            name='updated_at',
        ),
    ]
