# Generated by Django 3.2 on 2025-01-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0030_auto_20250114_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['id']},
        ),
    ]
