# Generated by Django 3.2 on 2025-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0032_auto_20250116_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(choices=[(1, 'Not Met (1)'), (2, 'Partially Met (2)'), (3, 'Met (3)'), (4, 'Exceptional (4)')]),
        ),
    ]
