# Generated by Django 3.2 on 2025-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0033_alter_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='status',
            field=models.CharField(choices=[('in_works', 'In Works'), ('current', 'Current'), ('expired', 'Expired')], default='current', max_length=20),
        ),
    ]
