# Generated by Django 3.2 on 2025-01-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0034_alter_accreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='status',
            field=models.CharField(choices=[('in_works', 'In Works'), ('current', 'Current'), ('retired', 'Retired')], default='current', max_length=20),
        ),
    ]
