# Generated by Django 3.2 on 2025-01-31 15:43

from django.db import migrations, models

def update_accreditation_status(apps, schema_editor):
    Accreditation = apps.get_model('accreditation', 'Accreditation')
    # Update old status values
    Accreditation.objects.filter(status='in_works').update(status='scheduled')
    Accreditation.objects.filter(status='current').update(status='active')
    Accreditation.objects.filter(status='retired').update(status='past')

class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0035_alter_accreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('past', 'Past')], default='scheduled', max_length=20),
        ),
    ]
