# Generated by Django 3.2 on 2025-01-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0037_accreditation_term_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='term_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
