# Generated by Django 3.2 on 2025-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0039_auto_20250202_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='previous_self_study_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
