# Generated by Django 5.2 on 2025-04-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0040_accreditation_previous_self_study_link'),
        ('users', '0120_school_board_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccreditationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_grade', models.CharField(max_length=5)),
                ('current_highest_grade', models.PositiveSmallIntegerField()),
                ('planned_highest_grade', models.PositiveSmallIntegerField()),
                ('anticipated_accreditation', models.CharField(blank=True, max_length=10, verbose_name='Anticipated School Year for Accreditation Site Visit')),
                ('date', models.DateField(auto_now_add=True)),
                ('ss_orientation_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
    ]
