# Generated by Django 5.2 on 2025-04-20 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0043_remove_accreditationapplication_site_visit_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
