# Generated by Django 5.2 on 2025-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0044_alter_accreditationapplication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='current_highest_grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='accreditationapplication',
            name='planned_highest_grade',
            field=models.CharField(max_length=5),
        ),
    ]
