# Generated by Django 5.2 on 2025-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0045_alter_accreditationapplication_current_highest_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='ss_orientation_date',
            field=models.DateField(blank=True, null=True, verbose_name='SelfStudy Orientation Date'),
        ),
    ]
