# Generated by Django 5.2 on 2025-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0046_alter_accreditationapplication_ss_orientation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='evidence_documents_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
