# Generated by Django 5.2 on 2025-04-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0047_accreditation_evidence_documents_link'),
        ('teachercert', '0131_alter_ceuinstance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear'),
        ),
    ]
