# Generated by Django 5.2 on 2025-05-04 08:53
# 0049_indicator_met_description.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0048_accreditation_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='met_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
