# Generated by Django 5.2 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0050_transfer_level_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
