# Generated by Django 5.2 on 2025-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0051_level_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator_Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Not Met (1)'), (2, 'Partially Met (2)'), (3, 'Met (3)'), (4, 'Exceptional (4)')])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='comment',
        ),
    ]
