# Generated by Django 5.2 on 2025-05-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0052_indicator_scores_remove_level_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicator_Scores',
            new_name='IndicatorScores',
        ),
        migrations.AlterModelOptions(
            name='indicatorscores',
            options={'ordering': ['-level']},
        ),
    ]
