# Generated by Django 5.2 on 2025-05-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0053_rename_indicator_scores_indicatorscores_and_more'),
        ('selfstudy', '0056_coursecategory_secondarycurriculumcourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorScores',
            new_name='IndicatorScore',
        ),
        migrations.AlterModelOptions(
            name='indicatorscore',
            options={'ordering': ['-score']},
        ),
        migrations.RenameField(
            model_name='indicatorscore',
            old_name='level',
            new_name='score',
        ),
    ]
