# Generated by Django 5.2 on 2025-09-24 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0058_populate_required_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationVisitingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team_membership', to='accreditation.accreditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('accreditation', 'user')},
            },
        ),
        migrations.AddField(
            model_name='accreditation',
            name='visiting_team',
            field=models.ManyToManyField(related_name='accreditation_team', through='accreditation.AccreditationVisitingTeam', to=settings.AUTH_USER_MODEL),
        ),
    ]
