# Generated by Django 5.2 on 2025-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0059_accreditationvisitingteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationvisitingteam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
