# Generated by Django 5.2 on 2025-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0060_accreditationvisitingteam_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationapplication',
            name='isei_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationapplication',
            name='isei_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accreditationapplication',
            name='ss_setup_date',
            field=models.DateField(blank=True, null=True, verbose_name='SelfStudy Setup Date'),
        ),
    ]
