# Generated by Django 5.2 on 2025-10-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0061_accreditationapplication_isei_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationapplication',
            name='accreditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.accreditation'),
        ),
    ]
