# Generated by Django 5.2 on 2025-10-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0062_accreditationapplication_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditationapplication',
            name='accreditation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.accreditation'),
        ),
    ]
