# Generated by Django 5.2 on 2025-10-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0063_alter_accreditationapplication_accreditation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditationapplication',
            name='site_visit_end_date',
        ),
        migrations.RemoveField(
            model_name='accreditationapplication',
            name='site_visit_start_date',
        ),
        migrations.RemoveField(
            model_name='accreditationapplication',
            name='ss_orientation_date',
        ),
        migrations.RemoveField(
            model_name='accreditationapplication',
            name='ss_setup_date',
        ),
    ]
