# Generated by Django 5.2 on 2025-10-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0064_remove_accreditationapplication_site_visit_end_date_and_more'),
        ('teachercert', '0139_alter_standardchecklist_faith_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accreditationapplication',
            name='anticipated_accreditation',
        ),
        migrations.AddField(
            model_name='accreditationapplication',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachercert.schoolyear', verbose_name='Anticipated School Year for Accreditation Site Visit'),
        ),
    ]
