# Generated by Django 5.2 on 2025-10-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0065_remove_accreditationapplication_anticipated_accreditation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accreditationapplication',
            old_name='isei_approval_date',
            new_name='isei_date',
        ),
    ]
