# Generated by Django 5.2 on 2025-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0066_rename_isei_approval_date_accreditationapplication_isei_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditationapplication',
            name='school_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
