# Generated by Django 5.2 on 2026-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0067_accreditationapplication_school_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='visiting_team_documents',
            field=models.URLField(blank=True, null=True),
        ),
    ]
