# Generated by Django 5.2 on 2026-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0068_accreditation_visiting_team_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requiredevidence',
            options={'ordering': ['order_number', 'name']},
        ),
        migrations.AlterModelOptions(
            name='requiredevidencecategory',
            options={'ordering': ['order_number', 'name']},
        ),
        migrations.AddField(
            model_name='requiredevidence',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requiredevidencecategory',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
