# Generated by Django 3.2 on 2025-01-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accreditation', '0026_alter_indicator_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinating_team', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Order Number')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInformationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinating_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='selfstudy.coordinatingteam')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.standard')),
            ],
        ),
        migrations.CreateModel(
            name='SelfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.accreditation')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_history', models.TextField(blank=True, null=True)),
                ('self_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.selfstudy')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInformationEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_years_ago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2 Years Ago')),
                ('one_year_ago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1 Year Ago')),
                ('financial_data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialinformationcategory')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDataEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=50, null=True)),
                ('other_financial_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialdata')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_financial_data', to='selfstudy.schoolprofile')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatingteam',
            name='self_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.selfstudy'),
        ),
    ]
