# Generated by Django 3.2 on 2025-01-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0002_auto_20250110_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financial2YearDataEntries',
            new_name='FinancialTwoYearDataEntries',
        ),
        migrations.RenameModel(
            old_name='Financial2YearDataKey',
            new_name='FinancialTwoYearDataKey',
        ),
        migrations.AlterField(
            model_name='financialadditionaldataentries',
            name='other_financial_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialadditionaldatakey'),
        ),
    ]
