# Generated by Django 3.2 on 2025-01-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0003_auto_20250110_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtwoyeardataentries',
            name='financial_data_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialtwoyeardatakey'),
        ),
    ]
