# Generated by Django 3.2 on 2025-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0004_alter_financialtwoyeardataentries_financial_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudy',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
