# Generated by Django 3.2 on 2025-01-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0030_auto_20250114_1527'),
        ('selfstudy', '0006_indicatorevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorevaluation',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accreditation.standard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicatorevaluation',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
