# Generated by Django 3.2 on 2025-01-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0031_alter_standard_options'),
        ('selfstudy', '0008_alter_indicatorevaluation_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinatingteam',
            old_name='self_study',
            new_name='selfstudy',
        ),
        migrations.RenameField(
            model_name='indicatorevaluation',
            old_name='self_study',
            new_name='selfstudy',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='self_study',
            new_name='selfstudy',
        ),
        migrations.AlterUniqueTogether(
            name='indicatorevaluation',
            unique_together={('selfstudy', 'indicator')},
        ),
    ]
