# Generated by Django 3.2 on 2025-01-16 15:29

from django.db import migrations, models

def fix_invalid_json(apps, schema_editor):
    IndicatorEvaluation = apps.get_model('selfstudy', 'IndicatorEvaluation')

    # Update rows with invalid data (empty string) to an empty list
    IndicatorEvaluation.objects.filter(reference_documents="").update(reference_documents=[])

class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0032_auto_20250116_1521'),
        ('selfstudy', '0011_auto_20250115_2119'),
    ]

    operations = [

        migrations.RunPython(fix_invalid_json),

        migrations.AlterModelOptions(
            name='indicatorevaluation',
            options={'ordering': ['selfstudy', 'standard', 'indicator']},
        ),
        migrations.AlterField(
            model_name='indicatorevaluation',
            name='reference_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='indicatorevaluation',
            index_together={('selfstudy', 'indicator'), ('selfstudy', 'standard')},
        ),
    ]
