# Generated by Django 3.2 on 2025-01-16 16:02

from django.db import migrations, models

def convert_json_to_text(apps, schema_editor):
    IndicatorEvaluation = apps.get_model('selfstudy', 'IndicatorEvaluation')
    IndicatorEvaluation.objects.filter(reference_documents="[]").update(reference_documents="")

class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0012_auto_20250116_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorevaluation',
            name='reference_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(convert_json_to_text),
    ]
