# Generated by Django 3.2 on 2025-01-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0033_alter_level_level'),
        ('selfstudy', '0015_auto_20250119_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudy',
            name='accreditation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accreditation.accreditation'),
        ),
    ]
