# Generated by Django 3.2 on 2025-01-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0016_alter_selfstudy_accreditation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Order Number')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.TextField(blank=True, null=True)),
                ('procedure_title_1', models.TextField(blank=True, null=True)),
                ('procedure_title_2', models.TextField(blank=True, null=True)),
                ('paragraphs', models.ManyToManyField(blank=True, related_name='paragraphs', to='selfstudy.InstructionSection')),
                ('procedure_group_1', models.ManyToManyField(blank=True, related_name='procedure_group_1', to='selfstudy.InstructionSection')),
                ('procedure_group_2', models.ManyToManyField(blank=True, related_name='procedure_group_2', to='selfstudy.InstructionSection')),
            ],
        ),
    ]
