# Generated by Django 3.2 on 2025-01-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0017_actionplaninstructions_instructionsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructionSection',
            new_name='ActionPlanInstructionSection',
        ),
        migrations.AddField(
            model_name='actionplaninstructions',
            name='procedure_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
