# Generated by Django 3.2 on 2025-01-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0020_coordinatingteam_standardteam_teammember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardteam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='standardteam',
            name='selfstudy',
        ),
        migrations.RemoveField(
            model_name='standardteam',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='coordinating_teams',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='standard_teams',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.DeleteModel(
            name='CoordinatingTeam',
        ),
        migrations.DeleteModel(
            name='StandardTeam',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
