# Generated by Django 3.2 on 2025-01-24 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0035_alter_accreditation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfstudy', '0021_auto_20250124_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('selfstudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='selfstudy.selfstudy')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.standard')),
            ],
            options={
                'unique_together': {('selfstudy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(related_name='members', to='selfstudy.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
