# Generated by Django 3.2 on 2025-01-26 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0035_alter_accreditation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfstudy', '0025_alter_teammember_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='SelfStudy_Team',
        ),
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='SelfStudy_TeamMember',
        ),
    ]
