# Generated by Django 3.2 on 2025-01-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0027_remove_selfstudy_teammember_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdditionalDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('data_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialadditionaldatakey')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_financial_data', to='selfstudy.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTwoYearDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_years_ago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2 Years Ago')),
                ('one_year_ago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='1 Year Ago')),
                ('data_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.financialtwoyeardatakey')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_year_financial_data', to='selfstudy.schoolprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialtwoyeardataentries',
            name='key',
        ),
        migrations.RemoveField(
            model_name='financialtwoyeardataentries',
            name='school_profile',
        ),
        migrations.DeleteModel(
            name='FinancialAdditionalDataEntries',
        ),
        migrations.DeleteModel(
            name='FinancialTwoYearDataEntries',
        ),
    ]
