# Generated by Django 3.2 on 2025-02-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0031_auto_20250202_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='zip/postal code'),
        ),
    ]
