# Generated by Django 3.2 on 2025-02-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0146_remove_reporttype_isei_created'),
        ('selfstudy', '0032_auto_20250202_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfStudyPersonnelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('VO', 'Volunteer'), ('NE', 'No Longer Employed'), ('LO', 'Leave of Absence')], default='FT', max_length=2, verbose_name='status')),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('certificaton_expire_date', models.DateField(blank=True, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_at_this_school', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.ManyToManyField(blank=True, to='reporting.StaffPosition', verbose_name='Assignment/Responsibility')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_data', to='selfstudy.schoolprofile')),
            ],
        ),
    ]
