# Generated by Django 3.2 on 2025-02-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0033_selfstudypersonneldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfstudypersonneldata',
            old_name='certificaton_expire_date',
            new_name='cert_renewal_date',
        ),
        migrations.AddField(
            model_name='selfstudypersonneldata',
            name='endorsements',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
