# Generated by Django 3.2 on 2025-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0034_auto_20250203_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfstudypersonneldata',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
