# Generated by Django 3.2 on 2025-02-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0035_selfstudypersonneldata_highest_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTEAssignmentKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order_number', models.PositiveSmallIntegerField(default=0, verbose_name='Order Number')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='FullTimeEquivalency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fte_men', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fte_women', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.fteassignmentkey')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_assignments', to='selfstudy.schoolprofile')),
            ],
        ),
    ]
