# Generated by Django 3.2 on 2025-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0036_fteassignmentkey_fulltimeequivalency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimeequivalency',
            name='fte_men',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fulltimeequivalency',
            name='fte_women',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
