# Generated by Django 3.2 on 2025-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0038_schoolprofile_fte_student_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfstudypersonneldata',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
