# Generated by Django 3.2 on 2025-02-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0039_selfstudypersonneldata_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_data', to='selfstudy.schoolprofile')),
            ],
        ),
    ]
