# Generated by Django 3.2 on 2025-02-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0040_studentenrollmentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('improvement', models.TextField(blank=True, null=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='selfstudy.schoolprofile')),
            ],
        ),
    ]
