# Generated by Django 3.2 on 2025-02-16 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0042_currentlyediting'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyediting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
