# Generated by Django 5.2 on 2025-04-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0043_currentlyediting_created_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indicatorevaluation',
            new_name='selfstudy_i_selfstu_62d84d_idx',
            old_fields=('selfstudy', 'standard'),
        ),
        migrations.RenameIndex(
            model_name='indicatorevaluation',
            new_name='selfstudy_i_selfstu_2ef09a_idx',
            old_fields=('selfstudy', 'indicator'),
        ),
    ]
