# Generated by Django 5.2 on 2025-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0044_rename_indicatorevaluation_selfstudy_standard_selfstudy_i_selfstu_62d84d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollmentdata',
            name='projected_enrollment_2_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollmentdata',
            name='projected_enrollment_3_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollmentdata',
            name='projected_enrollment_next_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
