# Generated by Django 5.2 on 2025-04-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0045_studentenrollmentdata_projected_enrollment_2_years_and_more'),
        ('teachercert', '0131_alter_ceuinstance_description'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('GEN', 'General Standardized Test'), ('ACT', 'ACT'), ('SAT', 'SAT')], max_length=4)),
                ('test_name', models.CharField(max_length=20)),
                ('is_elementary', models.BooleanField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='users.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='teachercert.schoolyear')),
            ],
            options={
                'unique_together': {('school', 'school_year', 'test_type', 'test_name', 'is_elementary')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_parents', models.TextField(blank=True, null=True)),
                ('process_to_improve', models.TextField(blank=True, null=True)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_data', to='selfstudy.schoolprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StandardizedTestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, max_length=10, null=True)),
                ('standardized_tests', models.TextField(blank=True, null=True)),
                ('student_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfstudy.studentachievementdata')),
            ],
        ),
        migrations.CreateModel(
            name='StandardizedTestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('READ', 'Reading'), ('WRIT', 'Writing'), ('MATH', 'Mathematics'), ('SCI', 'Science'), ('SOC', 'Social Studies'), ('COMP', 'Composite Score')], max_length=5)),
                ('grade', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='selfstudy.standardizedtestsession')),
            ],
            options={
                'unique_together': {('session', 'subject', 'grade')},
            },
        ),
    ]
