# Generated by Django 5.2 on 2025-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0046_standardizedtestsession_studentachievementdata_and_more'),
        ('teachercert', '0131_alter_ceuinstance_description'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardizedtestsession',
            unique_together={('school', 'school_year', 'test_type', 'test_name')},
        ),
        migrations.AddField(
            model_name='standardizedtestsession',
            name='grade_level_type',
            field=models.CharField(choices=[('elementary', 'Elementary'), ('secondary', 'Secondary')], default='secondary', max_length=10),
        ),
        migrations.RemoveField(
            model_name='standardizedtestsession',
            name='is_elementary',
        ),
    ]
