# Generated by Django 5.2 on 2025-04-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0048_alter_standardizedtestsession_unique_together'),
        ('teachercert', '0131_alter_ceuinstance_description'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardizedtestsession',
            unique_together={('school', 'school_year', 'test_type', 'grade_level_type')},
        ),
        migrations.AlterField(
            model_name='standardizedtestsession',
            name='test_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
