# Generated by Django 5.2 on 2025-04-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0050_gradeleveltest_delete_standardizedtestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestsession',
            name='test_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='standardizedtestsession',
            name='test_type',
            field=models.CharField(choices=[('IOWA', 'IOWA'), ('ACT', 'ACT'), ('SAT', 'SAT'), ('OT', 'OTHER')], max_length=10),
        ),
    ]
