# Generated by Django 5.2 on 2025-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0051_alter_standardizedtestsession_test_name_and_more'),
        ('teachercert', '0131_alter_ceuinstance_description'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardizedtestsession',
            unique_together={('school', 'school_year', 'test_type', 'test_name', 'grade_level_type')},
        ),
    ]
