# Generated by Django 5.2 on 2025-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0052_alter_standardizedtestsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestscore',
            name='subject',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('SOCIAL STUDIES', 'Social Studies'), ('COMPOSITE', 'Composite Score')], max_length=20),
        ),
    ]
