# Generated by Django 5.2 on 2025-05-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0055_philantrophyprogram_supportservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryCurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('certification_endorsed', models.BooleanField(default=False)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periods_per_week', models.PositiveIntegerField()),
                ('minutes_per_week', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='selfstudy.coursecategory')),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_curriculum', to='selfstudy.schoolprofile')),
            ],
        ),
    ]
