# Generated by Django 5.2 on 2025-05-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0054_rename_indicatorscores_indicatorscore_and_more'),
        ('selfstudy', '0056_coursecategory_secondarycurriculumcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorevaluation',
            name='indicator_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditation.indicatorscore'),
        ),
    ]
