# Generated by Django 5.2 on 2025-05-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0057_indicatorevaluation_indicator_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAndObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('vision_statement', models.TextField(blank=True, null=True)),
                ('philosophy_statement', models.TextField(blank=True, null=True)),
                ('school_objectives', models.TextField()),
                ('selfstudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='selfstudy.selfstudy')),
            ],
        ),
    ]
