# Generated by Django 5.2 on 2025-05-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0058_missionandobjectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalactivity',
            name='activity',
            field=models.CharField(max_length=255),
        ),
    ]
