# Generated by Django 5.2 on 2025-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0059_alter_professionalactivity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionandobjectives',
            name='school_objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
