# Generated by Django 5.2 on 2025-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0060_alter_missionandobjectives_school_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtwoyeardataentry',
            name='current_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Year to date'),
        ),
    ]
