# Generated by Django 5.2 on 2025-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0062_studentfollowupdatakey_studentfollowupdataentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfollowupdatakey',
            options={'ordering': ['order_number']},
        ),
        migrations.AddField(
            model_name='studentfollowupdatakey',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='studentfollowupdatakey',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Order Number'),
        ),
    ]
