# Generated by Django 5.2 on 2025-06-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0063_alter_studentfollowupdatakey_options_and_more'),
        ('teachercert', '0132_alter_ceuinstance_file_and_more'),
        ('users', '0131_alter_school_grade_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfollowupdataentry',
            name='one_year_ago',
        ),
        migrations.RemoveField(
            model_name='studentfollowupdataentry',
            name='school_profile',
        ),
        migrations.RemoveField(
            model_name='studentfollowupdataentry',
            name='two_years_ago',
        ),
        migrations.AddField(
            model_name='studentfollowupdataentry',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followup_entries', to='users.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfollowupdataentry',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followup_entries', to='teachercert.schoolyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfollowupdataentry',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
