# Generated by Django 5.2 on 2025-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0064_remove_studentfollowupdataentry_one_year_ago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCurriculumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dual_enrollment_number', models.SmallIntegerField(blank=True, null=True)),
                ('dual_enrollment_location', models.CharField(blank=True, max_length=2225, null=True)),
                ('dual_enrollment_courses', models.CharField(blank=True, max_length=2225, null=True)),
                ('vocational_certificate_areas', models.CharField(blank=True, max_length=2225, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentfollowupdatakey',
            options={'ordering': ['level', 'order_number']},
        ),
    ]
