# Generated by Django 5.2 on 2025-06-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0065_othercurriculumdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercurriculumdata',
            name='school_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_curriculum_data', to='selfstudy.schoolprofile'),
            preserve_default=False,
        ),
    ]
