# Generated by Django 5.2 on 2025-06-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0066_othercurriculumdata_school_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
