# Generated by Django 5.2 on 2025-09-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0067_alter_standardizedtestscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudy_teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_team', to='selfstudy.selfstudy_team'),
        ),
    ]
