# Generated by Django 5.2 on 2025-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0068_alter_selfstudy_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialadditionaldataentry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
