# Generated by Django 5.2 on 2025-12-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0069_financialadditionaldataentry_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialadditionaldataentry',
            name='comment',
        ),
    ]
