# Generated by Django 5.2 on 2025-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0070_remove_financialadditionaldataentry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='financial_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
