# Generated by Django 5.2 on 2026-01-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0071_schoolprofile_financial_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professionalactivity',
            unique_together={('school_profile', 'activity')},
        ),
    ]
