# Generated by Django 5.2 on 2026-02-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0073_visitingteamcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfstudy',
            old_name='last_updated',
            new_name='original_submission_date',
        ),
    ]
