# Generated by Django 5.2 on 2026-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0074_rename_last_updated_selfstudy_original_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudy',
            name='original_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
