# Generated by Django 5.2 on 2026-03-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0075_alter_selfstudy_original_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtwoyeardatakey',
            name='symbol',
            field=models.CharField(blank=True, default='$', max_length=5),
        ),
    ]
