# Generated by Django 5.2 on 2026-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0076_financialtwoyeardatakey_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestscore',
            name='score',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
