# Generated by Django 5.2 on 2026-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0077_alter_standardizedtestscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestscore',
            name='subject',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('NATIVE LANGUAGE', 'Native Language'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('SOCIAL STUDIES', 'Social Studies'), ('CIVICS', 'Civics'), ('COMPOSITE', 'Composite Score')], max_length=20),
        ),
    ]
