# Generated by Django 5.2 on 2026-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0078_alter_standardizedtestscore_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtestscore',
            name='subject',
            field=models.CharField(choices=[('COMPOSITE', 'Composite Score'), ('ENGLISH', 'English'), ('READING', 'Reading'), ('WRITING', 'Writing'), ('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('SOCIAL STUDIES', 'Social Studies'), ('NATIVE LANGUAGE', 'Native Language'), ('CIVICS', 'Civics'), ('HISTORY', 'History'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
