# Generated by Django 5.2 on 2026-07-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0081_currentlyediting_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyediting',
            name='editor_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
