# Generated by Django 5.2 on 2026-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0082_currentlyediting_editor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtwoyeardatakey',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
