# Generated by Django 5.2 on 2026-08-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0068_accreditation_visiting_team_documents'),
        ('selfstudy', '0084_indicatorevaluationhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorevaluationhistory',
            old_name='score',
            new_name='score_value',
        ),
        migrations.AddField(
            model_name='indicatorevaluationhistory',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.indicator'),
        ),
        migrations.AddField(
            model_name='indicatorevaluationhistory',
            name='indicator_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.indicatorscore'),
        ),
        migrations.AddField(
            model_name='indicatorevaluationhistory',
            name='selfstudy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selfstudy.selfstudy'),
        ),
        migrations.AddField(
            model_name='indicatorevaluationhistory',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.standard'),
        ),
        migrations.AlterField(
            model_name='indicatorevaluationhistory',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='selfstudy.indicatorevaluation'),
        ),
        migrations.AddIndex(
            model_name='indicatorevaluationhistory',
            index=models.Index(fields=['selfstudy', 'indicator'], name='selfstudy_i_selfstu_e14fb5_idx'),
        ),
    ]
