# Generated by Django 5.2 on 2026-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0085_rename_score_indicatorevaluationhistory_score_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtwoyeardataentry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='financialtwoyeardataentry',
            name='current_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Year to date'),
        ),
        migrations.AlterField(
            model_name='financialtwoyeardataentry',
            name='one_year_ago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='1 Year Ago'),
        ),
        migrations.AlterField(
            model_name='financialtwoyeardataentry',
            name='two_years_ago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='2 Years Ago'),
        ),
    ]
