# Generated by Django 5.2 on 2026-08-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfstudy', '0086_financialtwoyeardataentry_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtwoyeardataentry',
            name='currency',
        ),
    ]
