# Generated by Django 5.2 on 2026-08-21 13:16
from django.db import migrations


def add_currencies(apps, schema_editor):

    Currency = apps.get_model("selfstudy", "Currency")

    currencies = [
        ("USD", "US Dollar", "$"),
        ("EUR", "Euro", "€"),

        ("RON", "Romanian Leu", "lei"),

        ("PHP", "Philippine Peso", "₱"),

        ("KHR", "Cambodian Riel", "៛"),

        ("TZS", "Tanzanian Shilling", "TSh"),

        ("KRW", "South Korean Won", "₩"),

    ]

    for code, name, symbol in currencies:
        Currency.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "symbol": symbol,
            }
        )


def remove_currencies(apps, schema_editor):

    Currency = apps.get_model("selfstudy", "Currency")

    Currency.objects.filter(
        code__in=[
            "USD",
            "EUR",
            "RON",
            "PHP",
            "KHR",
            "TZS",
            "KRW",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("selfstudy", "0088_currency_schoolprofile_financial_currency"),
    ]

    operations = [
        migrations.RunPython(
            add_currencies,
            remove_currencies
        ),
    ]